-- ============================================================================

-- ============================================================================

SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

-- ============================================================
-- 1. ESPECIFICACIONES DE PACKAGES
-- ============================================================

CREATE OR REPLACE PACKAGE PKG_SEGURIDAD AS
    PROCEDURE SP_CREAR_USUARIO (
        P_ID_SITIO IN USUARIO.ID_SITIO%TYPE,
        P_CORREO IN USUARIO.CORREO%TYPE,
        P_TELEFONO IN USUARIO.TELEFONO%TYPE,
        P_FECHA_NACIMIENTO IN USUARIO.FECHA_NACIMIENTO%TYPE,
        P_NICKNAME IN USUARIO.NICKNAME%TYPE,
        P_PASSWORD_HASH IN USUARIO.PASSWORD_HASH%TYPE,
        P_TOKEN_QR_HASH IN USUARIO.TOKEN_QR_HASH%TYPE,
        P_NOTIFICA_EMAIL IN USUARIO.NOTIFICA_EMAIL%TYPE DEFAULT 'S',
        P_NOTIFICA_WHATSAPP IN USUARIO.NOTIFICA_WHATSAPP%TYPE DEFAULT 'N',
        O_ID_USUARIO OUT USUARIO.ID_USUARIO%TYPE
    );

    PROCEDURE SP_ASIGNAR_ROL (
        P_ID_USUARIO IN USUARIO.ID_USUARIO%TYPE,
        P_CODIGO_ROL IN ROL.CODIGO%TYPE
    );

    PROCEDURE SP_CAMBIAR_ESTADO_USUARIO (
        P_ID_USUARIO IN USUARIO.ID_USUARIO%TYPE,
        P_ACTIVO IN USUARIO.ACTIVO%TYPE,
        P_BLOQUEADO IN USUARIO.BLOQUEADO%TYPE
    );

    PROCEDURE SP_REGISTRAR_ACCESO (
        P_ID_USUARIO IN BITACORA_ACCESO.ID_USUARIO%TYPE,
        P_IDENTIFICADOR IN BITACORA_ACCESO.IDENTIFICADOR%TYPE,
        P_METODO_ACCESO IN BITACORA_ACCESO.METODO_ACCESO%TYPE,
        P_RESULTADO IN BITACORA_ACCESO.RESULTADO%TYPE,
        P_DIRECCION_IP IN BITACORA_ACCESO.DIRECCION_IP%TYPE DEFAULT NULL,
        P_UBICACION IN BITACORA_ACCESO.UBICACION%TYPE DEFAULT NULL,
        P_USER_AGENT IN BITACORA_ACCESO.USER_AGENT%TYPE DEFAULT NULL,
        P_MOTIVO IN BITACORA_ACCESO.MOTIVO%TYPE DEFAULT NULL,
        O_ID_BITACORA OUT BITACORA_ACCESO.ID_BITACORA%TYPE
    );

    PROCEDURE SP_OBTENER_AUTENTICACION (
        P_IDENTIFICADOR IN VARCHAR2,
        O_DATOS OUT SYS_REFCURSOR
    );

    PROCEDURE SP_LISTAR_PERMISOS (
        P_ID_USUARIO IN USUARIO.ID_USUARIO%TYPE,
        O_DATOS OUT SYS_REFCURSOR
    );
END PKG_SEGURIDAD;
/
SHOW ERRORS PACKAGE PKG_SEGURIDAD;

CREATE OR REPLACE PACKAGE PKG_ARCHIVO AS
    PROCEDURE SP_GUARDAR_ARCHIVO (
        P_ID_USUARIO_CARGA IN ARCHIVO.ID_USUARIO_CARGA%TYPE,
        P_TIPO_ARCHIVO IN ARCHIVO.TIPO_ARCHIVO%TYPE,
        P_NOMBRE_ARCHIVO IN ARCHIVO.NOMBRE_ARCHIVO%TYPE,
        P_MIME_TYPE IN ARCHIVO.MIME_TYPE%TYPE,
        P_HASH_SHA256 IN ARCHIVO.HASH_SHA256%TYPE,
        P_CONTENIDO IN ARCHIVO.CONTENIDO%TYPE,
        O_ID_ARCHIVO OUT ARCHIVO.ID_ARCHIVO%TYPE
    );

    PROCEDURE SP_OBTENER_ARCHIVO (
        P_ID_ARCHIVO IN ARCHIVO.ID_ARCHIVO%TYPE,
        O_DATOS OUT SYS_REFCURSOR
    );

    PROCEDURE SP_CAMBIAR_ESTADO (
        P_ID_ARCHIVO IN ARCHIVO.ID_ARCHIVO%TYPE,
        P_ACTIVO IN ARCHIVO.ACTIVO%TYPE
    );
END PKG_ARCHIVO;
/
SHOW ERRORS PACKAGE PKG_ARCHIVO;

CREATE OR REPLACE PACKAGE PKG_CATALOGO AS
    PROCEDURE SP_LISTAR_PRODUCTOS (
        P_ID_SITIO IN PRODUCTO.ID_SITIO%TYPE,
        P_ID_CATEGORIA IN PRODUCTO.ID_CATEGORIA%TYPE DEFAULT NULL,
        P_SOLO_ACTIVOS IN CHAR DEFAULT 'S',
        O_DATOS OUT SYS_REFCURSOR
    );

    PROCEDURE SP_OBTENER_PRODUCTO (
        P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE,
        O_DATOS OUT SYS_REFCURSOR
    );

    PROCEDURE SP_CREAR_PRODUCTO (
        P_ID_SITIO IN PRODUCTO.ID_SITIO%TYPE,
        P_ID_CATEGORIA IN PRODUCTO.ID_CATEGORIA%TYPE,
        P_ID_ARCHIVO_IMAGEN IN PRODUCTO.ID_ARCHIVO_IMAGEN%TYPE,
        P_SKU IN PRODUCTO.SKU%TYPE,
        P_NOMBRE IN PRODUCTO.NOMBRE%TYPE,
        P_DESCRIPCION IN PRODUCTO.DESCRIPCION%TYPE,
        P_PRECIO_BASE IN PRODUCTO.PRECIO_BASE%TYPE,
        P_PERMITE_LADO_A IN PRODUCTO.PERMITE_LADO_A%TYPE DEFAULT 'S',
        P_PERMITE_LADO_B IN PRODUCTO.PERMITE_LADO_B%TYPE DEFAULT 'S',
        O_ID_PRODUCTO OUT PRODUCTO.ID_PRODUCTO%TYPE
    );

    PROCEDURE SP_ACTUALIZAR_PRODUCTO (
        P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE,
        P_ID_CATEGORIA IN PRODUCTO.ID_CATEGORIA%TYPE,
        P_ID_ARCHIVO_IMAGEN IN PRODUCTO.ID_ARCHIVO_IMAGEN%TYPE,
        P_NOMBRE IN PRODUCTO.NOMBRE%TYPE,
        P_DESCRIPCION IN PRODUCTO.DESCRIPCION%TYPE,
        P_PRECIO_BASE IN PRODUCTO.PRECIO_BASE%TYPE,
        P_PERMITE_LADO_A IN PRODUCTO.PERMITE_LADO_A%TYPE,
        P_PERMITE_LADO_B IN PRODUCTO.PERMITE_LADO_B%TYPE
    );

    PROCEDURE SP_CAMBIAR_ESTADO_PRODUCTO (
        P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE,
        P_ACTIVO IN PRODUCTO.ACTIVO%TYPE
    );

    PROCEDURE SP_LISTAR_CATEGORIAS (
        P_SOLO_ACTIVAS IN CHAR DEFAULT 'S',
        O_DATOS OUT SYS_REFCURSOR
    );

    PROCEDURE SP_LISTAR_AREAS_ENTREGA (
        P_ID_SITIO IN AREA_ENTREGA.ID_SITIO%TYPE,
        P_SOLO_ACTIVAS IN CHAR DEFAULT 'S',
        O_DATOS OUT SYS_REFCURSOR
    );

    PROCEDURE SP_LISTAR_METODOS_PAGO (
        P_SOLO_ACTIVOS IN CHAR DEFAULT 'S',
        O_DATOS OUT SYS_REFCURSOR
    );
END PKG_CATALOGO;
/
SHOW ERRORS PACKAGE PKG_CATALOGO;

CREATE OR REPLACE PACKAGE PKG_CARRITO AS
    PROCEDURE SP_OBTENER_O_CREAR (
        P_ID_USUARIO IN CARRITO.ID_USUARIO%TYPE,
        P_ID_SITIO IN CARRITO.ID_SITIO%TYPE,
        O_ID_CARRITO OUT CARRITO.ID_CARRITO%TYPE
    );

    PROCEDURE SP_CREAR_PERSONALIZACION (
        P_ID_ARCHIVO_LADO_A IN PERSONALIZACION.ID_ARCHIVO_LADO_A%TYPE,
        P_ID_ARCHIVO_LADO_B IN PERSONALIZACION.ID_ARCHIVO_LADO_B%TYPE,
        P_MENSAJE_LADO_A IN PERSONALIZACION.MENSAJE_LADO_A%TYPE,
        P_MENSAJE_LADO_B IN PERSONALIZACION.MENSAJE_LADO_B%TYPE,
        P_CONFIG_LADO_A IN PERSONALIZACION.CONFIG_LADO_A%TYPE,
        P_CONFIG_LADO_B IN PERSONALIZACION.CONFIG_LADO_B%TYPE,
        O_ID_PERSONALIZACION OUT PERSONALIZACION.ID_PERSONALIZACION%TYPE
    );

    PROCEDURE SP_AGREGAR_PRODUCTO (
        P_ID_CARRITO IN CARRITO_DETALLE.ID_CARRITO%TYPE,
        P_ID_PRODUCTO IN CARRITO_DETALLE.ID_PRODUCTO%TYPE,
        P_ID_PERSONALIZACION IN CARRITO_DETALLE.ID_PERSONALIZACION%TYPE,
        P_CANTIDAD IN CARRITO_DETALLE.CANTIDAD%TYPE,
        P_PRECIO_PERSONALIZA IN CARRITO_DETALLE.PRECIO_PERSONALIZA%TYPE DEFAULT 0,
        O_ID_CARRITO_DETALLE OUT CARRITO_DETALLE.ID_CARRITO_DETALLE%TYPE
    );

    PROCEDURE SP_ACTUALIZAR_CANTIDAD (
        P_ID_CARRITO_DETALLE IN CARRITO_DETALLE.ID_CARRITO_DETALLE%TYPE,
        P_CANTIDAD IN CARRITO_DETALLE.CANTIDAD%TYPE
    );

    PROCEDURE SP_ELIMINAR_DETALLE (
        P_ID_CARRITO_DETALLE IN CARRITO_DETALLE.ID_CARRITO_DETALLE%TYPE
    );

    PROCEDURE SP_OBTENER_CARRITO (
        P_ID_CARRITO IN CARRITO.ID_CARRITO%TYPE,
        O_DATOS OUT SYS_REFCURSOR
    );

    PROCEDURE SP_ABANDONAR_CARRITO (
        P_ID_CARRITO IN CARRITO.ID_CARRITO%TYPE
    );
END PKG_CARRITO;
/
SHOW ERRORS PACKAGE PKG_CARRITO;

CREATE OR REPLACE PACKAGE PKG_PEDIDO AS
    PROCEDURE SP_CREAR_DESDE_CARRITO (
        P_ID_CARRITO IN CARRITO.ID_CARRITO%TYPE,
        P_ID_AREA_ENTREGA IN AREA_ENTREGA.ID_AREA_ENTREGA%TYPE,
        P_NUMERO_PEDIDO IN PEDIDO.NUMERO_PEDIDO%TYPE,
        P_TOKEN_QR_HASH IN PEDIDO.TOKEN_QR_HASH%TYPE,
        P_COD_MONEDA IN PEDIDO.COD_MONEDA%TYPE DEFAULT 'GTQ',
        P_REFERENCIA_ENTREGA IN PEDIDO.REFERENCIA_ENTREGA%TYPE DEFAULT NULL,
        P_OBSERVACIONES IN PEDIDO.OBSERVACIONES%TYPE DEFAULT NULL,
        O_ID_PEDIDO OUT PEDIDO.ID_PEDIDO%TYPE
    );

    PROCEDURE SP_CAMBIAR_ESTADO (
        P_ID_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE,
        P_CODIGO_ESTADO IN ESTADO_PEDIDO.CODIGO%TYPE,
        P_ID_USUARIO_ACTOR IN PEDIDO_ESTADO_HISTORIAL.ID_USUARIO_ACTOR%TYPE,
        P_COMENTARIO IN PEDIDO_ESTADO_HISTORIAL.COMENTARIO%TYPE DEFAULT NULL,
        P_DIRECCION_IP IN PEDIDO_ESTADO_HISTORIAL.DIRECCION_IP%TYPE DEFAULT NULL
    );

    PROCEDURE SP_OBTENER_RESUMEN (P_ID_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE, O_DATOS OUT SYS_REFCURSOR);
    PROCEDURE SP_OBTENER_DETALLE (P_ID_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE, O_DATOS OUT SYS_REFCURSOR);
    PROCEDURE SP_LISTAR_POR_USUARIO (P_ID_USUARIO IN PEDIDO.ID_USUARIO%TYPE, O_DATOS OUT SYS_REFCURSOR);
    PROCEDURE SP_CONSULTAR_TRACKING (P_TOKEN_QR_HASH IN PEDIDO.TOKEN_QR_HASH%TYPE, O_DATOS OUT SYS_REFCURSOR);
END PKG_PEDIDO;
/
SHOW ERRORS PACKAGE PKG_PEDIDO;

CREATE OR REPLACE PACKAGE PKG_PAGO_ENTREGA AS
    PROCEDURE SP_REGISTRAR_PAGO (
        P_ID_PEDIDO IN PAGO.ID_PEDIDO%TYPE,
        P_CODIGO_METODO IN METODO_PAGO.CODIGO%TYPE,
        P_CODIGO_ESTADO IN ESTADO_PAGO.CODIGO%TYPE DEFAULT 'PENDIENTE',
        P_MONTO IN PAGO.MONTO%TYPE,
        P_PROVEEDOR_PAGO IN PAGO.PROVEEDOR_PAGO%TYPE DEFAULT NULL,
        P_REFERENCIA_PROV IN PAGO.REFERENCIA_PROV%TYPE DEFAULT NULL,
        P_MARCA_TARJETA IN PAGO.MARCA_TARJETA%TYPE DEFAULT NULL,
        P_ULTIMOS_4 IN PAGO.ULTIMOS_4%TYPE DEFAULT NULL,
        P_OBSERVACIONES IN PAGO.OBSERVACIONES%TYPE DEFAULT NULL,
        O_ID_PAGO OUT PAGO.ID_PAGO%TYPE
    );

    PROCEDURE SP_CAMBIAR_ESTADO_PAGO (
        P_ID_PAGO IN PAGO.ID_PAGO%TYPE,
        P_CODIGO_ESTADO IN ESTADO_PAGO.CODIGO%TYPE,
        P_OBSERVACIONES IN PAGO.OBSERVACIONES%TYPE DEFAULT NULL
    );

    PROCEDURE SP_LISTAR_PAGOS_PEDIDO (P_ID_PEDIDO IN PAGO.ID_PEDIDO%TYPE, O_DATOS OUT SYS_REFCURSOR);

    PROCEDURE SP_ASIGNAR_ENTREGA (
        P_ID_PEDIDO IN ENTREGA.ID_PEDIDO%TYPE,
        P_ID_REPARTIDOR IN ENTREGA.ID_REPARTIDOR%TYPE,
        O_ID_ENTREGA OUT ENTREGA.ID_ENTREGA%TYPE
    );

    PROCEDURE SP_REGISTRAR_RESULTADO_ENTREGA (
        P_ID_ENTREGA IN ENTREGA.ID_ENTREGA%TYPE,
        P_CODIGO_ESTADO IN ESTADO_ENTREGA.CODIGO%TYPE,
        P_ID_ARCHIVO_EVIDENCIA IN ENTREGA.ID_ARCHIVO_EVIDENCIA%TYPE DEFAULT NULL,
        P_MONTO_EFECTIVO IN ENTREGA.MONTO_EFECTIVO%TYPE DEFAULT 0,
        P_OBSERVACIONES IN ENTREGA.OBSERVACIONES%TYPE DEFAULT NULL,
        P_ID_USUARIO_ACTOR IN USUARIO.ID_USUARIO%TYPE DEFAULT NULL
    );

    PROCEDURE SP_LISTAR_ENTREGAS_REPARTIDOR (
        P_ID_REPARTIDOR IN ENTREGA.ID_REPARTIDOR%TYPE,
        O_DATOS OUT SYS_REFCURSOR
    );
END PKG_PAGO_ENTREGA;
/
SHOW ERRORS PACKAGE PKG_PAGO_ENTREGA;

-- ============================================================
-- 2. CUERPOS DE PACKAGES
-- ============================================================

CREATE OR REPLACE PACKAGE BODY PKG_SEGURIDAD AS
    PROCEDURE SP_CREAR_USUARIO (
        P_ID_SITIO IN USUARIO.ID_SITIO%TYPE,
        P_CORREO IN USUARIO.CORREO%TYPE,
        P_TELEFONO IN USUARIO.TELEFONO%TYPE,
        P_FECHA_NACIMIENTO IN USUARIO.FECHA_NACIMIENTO%TYPE,
        P_NICKNAME IN USUARIO.NICKNAME%TYPE,
        P_PASSWORD_HASH IN USUARIO.PASSWORD_HASH%TYPE,
        P_TOKEN_QR_HASH IN USUARIO.TOKEN_QR_HASH%TYPE,
        P_NOTIFICA_EMAIL IN USUARIO.NOTIFICA_EMAIL%TYPE,
        P_NOTIFICA_WHATSAPP IN USUARIO.NOTIFICA_WHATSAPP%TYPE,
        O_ID_USUARIO OUT USUARIO.ID_USUARIO%TYPE
    ) AS
        V_ID_ROL ROL.ID_ROL%TYPE;
        V_EXISTE NUMBER;
    BEGIN
        IF P_NOTIFICA_EMAIL NOT IN ('S','N') OR P_NOTIFICA_WHATSAPP NOT IN ('S','N')
           OR (P_NOTIFICA_EMAIL = 'N' AND P_NOTIFICA_WHATSAPP = 'N') THEN
            RAISE_APPLICATION_ERROR(-20101, 'Debe habilitar al menos un medio de notificacion.');
        END IF;

        SELECT COUNT(*) INTO V_EXISTE FROM SITIO
         WHERE ID_SITIO = P_ID_SITIO AND ACTIVO = 'S';
        IF V_EXISTE = 0 THEN
            RAISE_APPLICATION_ERROR(-20102, 'El sitio no existe o esta inactivo.');
        END IF;

        SELECT ID_ROL INTO V_ID_ROL FROM ROL
         WHERE CODIGO = 'COMPRADOR' AND ACTIVO = 'S';

        INSERT INTO USUARIO (
            ID_SITIO, CORREO, TELEFONO, FECHA_NACIMIENTO, NICKNAME,
            PASSWORD_HASH, TOKEN_QR_HASH, NOTIFICA_EMAIL, NOTIFICA_WHATSAPP
        ) VALUES (
            P_ID_SITIO, TRIM(P_CORREO), TRIM(P_TELEFONO), P_FECHA_NACIMIENTO,
            TRIM(P_NICKNAME), P_PASSWORD_HASH, P_TOKEN_QR_HASH,
            P_NOTIFICA_EMAIL, P_NOTIFICA_WHATSAPP
        ) RETURNING ID_USUARIO INTO O_ID_USUARIO;

        INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
        VALUES (O_ID_USUARIO, V_ID_ROL);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20103, 'El correo, nickname o token QR ya esta registrado.');
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20104, 'No existe el rol activo COMPRADOR.');
    END SP_CREAR_USUARIO;

    PROCEDURE SP_ASIGNAR_ROL (
        P_ID_USUARIO IN USUARIO.ID_USUARIO%TYPE,
        P_CODIGO_ROL IN ROL.CODIGO%TYPE
    ) AS
        V_ID_ROL ROL.ID_ROL%TYPE;
        V_EXISTE NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_EXISTE FROM USUARIO WHERE ID_USUARIO = P_ID_USUARIO;
        IF V_EXISTE = 0 THEN RAISE_APPLICATION_ERROR(-20105, 'El usuario no existe.'); END IF;

        SELECT ID_ROL INTO V_ID_ROL FROM ROL
         WHERE CODIGO = UPPER(TRIM(P_CODIGO_ROL)) AND ACTIVO = 'S';

        MERGE INTO USUARIO_ROL UR
        USING (SELECT P_ID_USUARIO ID_USUARIO, V_ID_ROL ID_ROL FROM DUAL) X
           ON (UR.ID_USUARIO = X.ID_USUARIO AND UR.ID_ROL = X.ID_ROL)
        WHEN NOT MATCHED THEN
            INSERT (ID_USUARIO, ID_ROL) VALUES (X.ID_USUARIO, X.ID_ROL);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20106, 'El rol no existe o esta inactivo.');
    END SP_ASIGNAR_ROL;

    PROCEDURE SP_CAMBIAR_ESTADO_USUARIO (
        P_ID_USUARIO IN USUARIO.ID_USUARIO%TYPE,
        P_ACTIVO IN USUARIO.ACTIVO%TYPE,
        P_BLOQUEADO IN USUARIO.BLOQUEADO%TYPE
    ) AS
    BEGIN
        IF P_ACTIVO NOT IN ('S','N') OR P_BLOQUEADO NOT IN ('S','N') THEN
            RAISE_APPLICATION_ERROR(-20107, 'Los estados deben ser S o N.');
        END IF;
        UPDATE USUARIO SET ACTIVO = P_ACTIVO, BLOQUEADO = P_BLOQUEADO
         WHERE ID_USUARIO = P_ID_USUARIO;
        IF SQL%ROWCOUNT = 0 THEN RAISE_APPLICATION_ERROR(-20108, 'El usuario no existe.'); END IF;
    END SP_CAMBIAR_ESTADO_USUARIO;

    PROCEDURE SP_REGISTRAR_ACCESO (
        P_ID_USUARIO IN BITACORA_ACCESO.ID_USUARIO%TYPE,
        P_IDENTIFICADOR IN BITACORA_ACCESO.IDENTIFICADOR%TYPE,
        P_METODO_ACCESO IN BITACORA_ACCESO.METODO_ACCESO%TYPE,
        P_RESULTADO IN BITACORA_ACCESO.RESULTADO%TYPE,
        P_DIRECCION_IP IN BITACORA_ACCESO.DIRECCION_IP%TYPE,
        P_UBICACION IN BITACORA_ACCESO.UBICACION%TYPE,
        P_USER_AGENT IN BITACORA_ACCESO.USER_AGENT%TYPE,
        P_MOTIVO IN BITACORA_ACCESO.MOTIVO%TYPE,
        O_ID_BITACORA OUT BITACORA_ACCESO.ID_BITACORA%TYPE
    ) AS
    BEGIN
        INSERT INTO BITACORA_ACCESO (
            ID_USUARIO, IDENTIFICADOR, METODO_ACCESO, RESULTADO,
            DIRECCION_IP, UBICACION, USER_AGENT, MOTIVO
        ) VALUES (
            P_ID_USUARIO, P_IDENTIFICADOR, UPPER(TRIM(P_METODO_ACCESO)), P_RESULTADO,
            P_DIRECCION_IP, P_UBICACION, P_USER_AGENT, P_MOTIVO
        ) RETURNING ID_BITACORA INTO O_ID_BITACORA;
    END SP_REGISTRAR_ACCESO;

    PROCEDURE SP_OBTENER_AUTENTICACION (P_IDENTIFICADOR IN VARCHAR2, O_DATOS OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN O_DATOS FOR
            SELECT ID_USUARIO, ID_SITIO, CORREO, NICKNAME, PASSWORD_HASH,
                   TOKEN_QR_HASH, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, ULTIMO_ACCESO
              FROM USUARIO
             WHERE LOWER(CORREO) = LOWER(TRIM(P_IDENTIFICADOR))
                OR LOWER(NICKNAME) = LOWER(TRIM(P_IDENTIFICADOR));
    END SP_OBTENER_AUTENTICACION;

    PROCEDURE SP_LISTAR_PERMISOS (P_ID_USUARIO IN USUARIO.ID_USUARIO%TYPE, O_DATOS OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN O_DATOS FOR
            SELECT DISTINCT R.CODIGO CODIGO_ROL, R.NOMBRE ROL,
                   P.CODIGO CODIGO_PERMISO, P.NOMBRE PERMISO, P.MODULO
              FROM USUARIO_ROL UR
              JOIN ROL R ON R.ID_ROL = UR.ID_ROL AND R.ACTIVO = 'S'
              JOIN ROL_PERMISO RP ON RP.ID_ROL = R.ID_ROL
              JOIN PERMISO P ON P.ID_PERMISO = RP.ID_PERMISO AND P.ACTIVO = 'S'
             WHERE UR.ID_USUARIO = P_ID_USUARIO
             ORDER BY P.MODULO, P.CODIGO;
    END SP_LISTAR_PERMISOS;
END PKG_SEGURIDAD;
/
SHOW ERRORS PACKAGE BODY PKG_SEGURIDAD;

CREATE OR REPLACE PACKAGE BODY PKG_ARCHIVO AS
    PROCEDURE SP_GUARDAR_ARCHIVO (
        P_ID_USUARIO_CARGA IN ARCHIVO.ID_USUARIO_CARGA%TYPE,
        P_TIPO_ARCHIVO IN ARCHIVO.TIPO_ARCHIVO%TYPE,
        P_NOMBRE_ARCHIVO IN ARCHIVO.NOMBRE_ARCHIVO%TYPE,
        P_MIME_TYPE IN ARCHIVO.MIME_TYPE%TYPE,
        P_HASH_SHA256 IN ARCHIVO.HASH_SHA256%TYPE,
        P_CONTENIDO IN ARCHIVO.CONTENIDO%TYPE,
        O_ID_ARCHIVO OUT ARCHIVO.ID_ARCHIVO%TYPE
    ) AS
        V_TAMANO ARCHIVO.TAMANO_BYTES%TYPE;
    BEGIN
        IF P_CONTENIDO IS NULL THEN RAISE_APPLICATION_ERROR(-20201, 'El contenido es obligatorio.'); END IF;
        V_TAMANO := DBMS_LOB.GETLENGTH(P_CONTENIDO);
        INSERT INTO ARCHIVO (
            ID_USUARIO_CARGA, TIPO_ARCHIVO, NOMBRE_ARCHIVO,
            MIME_TYPE, TAMANO_BYTES, HASH_SHA256, CONTENIDO
        ) VALUES (
            P_ID_USUARIO_CARGA, UPPER(TRIM(P_TIPO_ARCHIVO)), TRIM(P_NOMBRE_ARCHIVO),
            LOWER(TRIM(P_MIME_TYPE)), V_TAMANO, LOWER(TRIM(P_HASH_SHA256)), P_CONTENIDO
        ) RETURNING ID_ARCHIVO INTO O_ID_ARCHIVO;
    END SP_GUARDAR_ARCHIVO;

    PROCEDURE SP_OBTENER_ARCHIVO (P_ID_ARCHIVO IN ARCHIVO.ID_ARCHIVO%TYPE, O_DATOS OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN O_DATOS FOR
            SELECT ID_ARCHIVO, ID_USUARIO_CARGA, TIPO_ARCHIVO, NOMBRE_ARCHIVO,
                   MIME_TYPE, TAMANO_BYTES, HASH_SHA256, CONTENIDO, FECHA_CARGA
              FROM ARCHIVO WHERE ID_ARCHIVO = P_ID_ARCHIVO AND ACTIVO = 'S';
    END SP_OBTENER_ARCHIVO;

    PROCEDURE SP_CAMBIAR_ESTADO (P_ID_ARCHIVO IN ARCHIVO.ID_ARCHIVO%TYPE, P_ACTIVO IN ARCHIVO.ACTIVO%TYPE) AS
    BEGIN
        IF P_ACTIVO NOT IN ('S','N') THEN RAISE_APPLICATION_ERROR(-20202, 'El estado debe ser S o N.'); END IF;
        UPDATE ARCHIVO SET ACTIVO = P_ACTIVO WHERE ID_ARCHIVO = P_ID_ARCHIVO;
        IF SQL%ROWCOUNT = 0 THEN RAISE_APPLICATION_ERROR(-20203, 'El archivo no existe.'); END IF;
    END SP_CAMBIAR_ESTADO;
END PKG_ARCHIVO;
/
SHOW ERRORS PACKAGE BODY PKG_ARCHIVO;

CREATE OR REPLACE PACKAGE BODY PKG_CATALOGO AS
    PROCEDURE SP_LISTAR_PRODUCTOS (
        P_ID_SITIO IN PRODUCTO.ID_SITIO%TYPE,
        P_ID_CATEGORIA IN PRODUCTO.ID_CATEGORIA%TYPE,
        P_SOLO_ACTIVOS IN CHAR,
        O_DATOS OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN O_DATOS FOR
            SELECT P.ID_PRODUCTO, P.ID_SITIO, P.ID_CATEGORIA,
                   C.CODIGO CODIGO_CATEGORIA, C.NOMBRE CATEGORIA,
                   P.ID_ARCHIVO_IMAGEN, P.SKU, P.NOMBRE, P.DESCRIPCION,
                   P.PRECIO_BASE, P.PERMITE_LADO_A, P.PERMITE_LADO_B, P.ACTIVO
              FROM PRODUCTO P
              JOIN CATEGORIA_PRODUCTO C ON C.ID_CATEGORIA = P.ID_CATEGORIA
             WHERE P.ID_SITIO = P_ID_SITIO
               AND (P_ID_CATEGORIA IS NULL OR P.ID_CATEGORIA = P_ID_CATEGORIA)
               AND (P_SOLO_ACTIVOS = 'N' OR P.ACTIVO = 'S')
             ORDER BY C.NOMBRE, P.NOMBRE;
    END SP_LISTAR_PRODUCTOS;

    PROCEDURE SP_OBTENER_PRODUCTO (P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE, O_DATOS OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN O_DATOS FOR
            SELECT P.ID_PRODUCTO, P.ID_SITIO, S.NOMBRE SITIO,
                   P.ID_CATEGORIA, C.NOMBRE CATEGORIA, P.ID_ARCHIVO_IMAGEN,
                   P.SKU, P.NOMBRE, P.DESCRIPCION, P.PRECIO_BASE,
                   P.PERMITE_LADO_A, P.PERMITE_LADO_B, P.ACTIVO,
                   P.FECHA_CREACION, P.FECHA_MODIFICACION
              FROM PRODUCTO P
              JOIN SITIO S ON S.ID_SITIO = P.ID_SITIO
              JOIN CATEGORIA_PRODUCTO C ON C.ID_CATEGORIA = P.ID_CATEGORIA
             WHERE P.ID_PRODUCTO = P_ID_PRODUCTO;
    END SP_OBTENER_PRODUCTO;

    PROCEDURE SP_CREAR_PRODUCTO (
        P_ID_SITIO IN PRODUCTO.ID_SITIO%TYPE,
        P_ID_CATEGORIA IN PRODUCTO.ID_CATEGORIA%TYPE,
        P_ID_ARCHIVO_IMAGEN IN PRODUCTO.ID_ARCHIVO_IMAGEN%TYPE,
        P_SKU IN PRODUCTO.SKU%TYPE,
        P_NOMBRE IN PRODUCTO.NOMBRE%TYPE,
        P_DESCRIPCION IN PRODUCTO.DESCRIPCION%TYPE,
        P_PRECIO_BASE IN PRODUCTO.PRECIO_BASE%TYPE,
        P_PERMITE_LADO_A IN PRODUCTO.PERMITE_LADO_A%TYPE,
        P_PERMITE_LADO_B IN PRODUCTO.PERMITE_LADO_B%TYPE,
        O_ID_PRODUCTO OUT PRODUCTO.ID_PRODUCTO%TYPE
    ) AS
    BEGIN
        IF P_PRECIO_BASE < 0 THEN RAISE_APPLICATION_ERROR(-20301, 'El precio no puede ser negativo.'); END IF;
        INSERT INTO PRODUCTO (
            ID_SITIO, ID_CATEGORIA, ID_ARCHIVO_IMAGEN, SKU, NOMBRE,
            DESCRIPCION, PRECIO_BASE, PERMITE_LADO_A, PERMITE_LADO_B
        ) VALUES (
            P_ID_SITIO, P_ID_CATEGORIA, P_ID_ARCHIVO_IMAGEN, UPPER(TRIM(P_SKU)),
            TRIM(P_NOMBRE), P_DESCRIPCION, P_PRECIO_BASE, P_PERMITE_LADO_A, P_PERMITE_LADO_B
        ) RETURNING ID_PRODUCTO INTO O_ID_PRODUCTO;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20302, 'Ya existe el SKU en este sitio.');
    END SP_CREAR_PRODUCTO;

    PROCEDURE SP_ACTUALIZAR_PRODUCTO (
        P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE,
        P_ID_CATEGORIA IN PRODUCTO.ID_CATEGORIA%TYPE,
        P_ID_ARCHIVO_IMAGEN IN PRODUCTO.ID_ARCHIVO_IMAGEN%TYPE,
        P_NOMBRE IN PRODUCTO.NOMBRE%TYPE,
        P_DESCRIPCION IN PRODUCTO.DESCRIPCION%TYPE,
        P_PRECIO_BASE IN PRODUCTO.PRECIO_BASE%TYPE,
        P_PERMITE_LADO_A IN PRODUCTO.PERMITE_LADO_A%TYPE,
        P_PERMITE_LADO_B IN PRODUCTO.PERMITE_LADO_B%TYPE
    ) AS
    BEGIN
        IF P_PRECIO_BASE < 0 THEN RAISE_APPLICATION_ERROR(-20303, 'El precio no puede ser negativo.'); END IF;
        UPDATE PRODUCTO
           SET ID_CATEGORIA = P_ID_CATEGORIA,
               ID_ARCHIVO_IMAGEN = P_ID_ARCHIVO_IMAGEN,
               NOMBRE = TRIM(P_NOMBRE), DESCRIPCION = P_DESCRIPCION,
               PRECIO_BASE = P_PRECIO_BASE, PERMITE_LADO_A = P_PERMITE_LADO_A,
               PERMITE_LADO_B = P_PERMITE_LADO_B
         WHERE ID_PRODUCTO = P_ID_PRODUCTO;
        IF SQL%ROWCOUNT = 0 THEN RAISE_APPLICATION_ERROR(-20304, 'El producto no existe.'); END IF;
    END SP_ACTUALIZAR_PRODUCTO;

    PROCEDURE SP_CAMBIAR_ESTADO_PRODUCTO (P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE, P_ACTIVO IN PRODUCTO.ACTIVO%TYPE) AS
    BEGIN
        IF P_ACTIVO NOT IN ('S','N') THEN RAISE_APPLICATION_ERROR(-20305, 'El estado debe ser S o N.'); END IF;
        UPDATE PRODUCTO SET ACTIVO = P_ACTIVO WHERE ID_PRODUCTO = P_ID_PRODUCTO;
        IF SQL%ROWCOUNT = 0 THEN RAISE_APPLICATION_ERROR(-20306, 'El producto no existe.'); END IF;
    END SP_CAMBIAR_ESTADO_PRODUCTO;

    PROCEDURE SP_LISTAR_CATEGORIAS (P_SOLO_ACTIVAS IN CHAR, O_DATOS OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN O_DATOS FOR
            SELECT ID_CATEGORIA, CODIGO, NOMBRE, DESCRIPCION, ACTIVO
              FROM CATEGORIA_PRODUCTO
             WHERE P_SOLO_ACTIVAS = 'N' OR ACTIVO = 'S'
             ORDER BY NOMBRE;
    END SP_LISTAR_CATEGORIAS;

    PROCEDURE SP_LISTAR_AREAS_ENTREGA (
        P_ID_SITIO IN AREA_ENTREGA.ID_SITIO%TYPE,
        P_SOLO_ACTIVAS IN CHAR,
        O_DATOS OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN O_DATOS FOR
            SELECT ID_AREA_ENTREGA, ID_SITIO, CODIGO, NOMBRE,
                   TIPO_AREA, REFERENCIA, CARGO_ENTREGA, ACTIVO
              FROM AREA_ENTREGA
             WHERE ID_SITIO = P_ID_SITIO
               AND (P_SOLO_ACTIVAS = 'N' OR ACTIVO = 'S')
             ORDER BY NOMBRE;
    END SP_LISTAR_AREAS_ENTREGA;

    PROCEDURE SP_LISTAR_METODOS_PAGO (P_SOLO_ACTIVOS IN CHAR, O_DATOS OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN O_DATOS FOR
            SELECT ID_METODO_PAGO, CODIGO, NOMBRE, REQUIERE_PROVEEDOR, ACTIVO
              FROM METODO_PAGO
             WHERE P_SOLO_ACTIVOS = 'N' OR ACTIVO = 'S'
             ORDER BY NOMBRE;
    END SP_LISTAR_METODOS_PAGO;
END PKG_CATALOGO;
/
SHOW ERRORS PACKAGE BODY PKG_CATALOGO;

CREATE OR REPLACE PACKAGE BODY PKG_CARRITO AS
    PROCEDURE SP_OBTENER_O_CREAR (
        P_ID_USUARIO IN CARRITO.ID_USUARIO%TYPE,
        P_ID_SITIO IN CARRITO.ID_SITIO%TYPE,
        O_ID_CARRITO OUT CARRITO.ID_CARRITO%TYPE
    ) AS
        V_EXISTE NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_EXISTE
          FROM USUARIO U JOIN SITIO S ON S.ID_SITIO = P_ID_SITIO
         WHERE U.ID_USUARIO = P_ID_USUARIO AND U.ID_SITIO = P_ID_SITIO
           AND U.ACTIVO = 'S' AND U.BLOQUEADO = 'N' AND S.ACTIVO = 'S';
        IF V_EXISTE = 0 THEN
            RAISE_APPLICATION_ERROR(-20401, 'El usuario o sitio no es valido.');
        END IF;

        BEGIN
            SELECT ID_CARRITO INTO O_ID_CARRITO
              FROM CARRITO
             WHERE ID_USUARIO = P_ID_USUARIO AND ID_SITIO = P_ID_SITIO AND ESTADO = 'ABIERTO';
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                BEGIN
                    INSERT INTO CARRITO (ID_USUARIO, ID_SITIO)
                    VALUES (P_ID_USUARIO, P_ID_SITIO)
                    RETURNING ID_CARRITO INTO O_ID_CARRITO;
                EXCEPTION
                    WHEN DUP_VAL_ON_INDEX THEN
                        SELECT ID_CARRITO INTO O_ID_CARRITO FROM CARRITO
                         WHERE ID_USUARIO = P_ID_USUARIO AND ID_SITIO = P_ID_SITIO AND ESTADO = 'ABIERTO';
                END;
        END;
    END SP_OBTENER_O_CREAR;

    PROCEDURE SP_CREAR_PERSONALIZACION (
        P_ID_ARCHIVO_LADO_A IN PERSONALIZACION.ID_ARCHIVO_LADO_A%TYPE,
        P_ID_ARCHIVO_LADO_B IN PERSONALIZACION.ID_ARCHIVO_LADO_B%TYPE,
        P_MENSAJE_LADO_A IN PERSONALIZACION.MENSAJE_LADO_A%TYPE,
        P_MENSAJE_LADO_B IN PERSONALIZACION.MENSAJE_LADO_B%TYPE,
        P_CONFIG_LADO_A IN PERSONALIZACION.CONFIG_LADO_A%TYPE,
        P_CONFIG_LADO_B IN PERSONALIZACION.CONFIG_LADO_B%TYPE,
        O_ID_PERSONALIZACION OUT PERSONALIZACION.ID_PERSONALIZACION%TYPE
    ) AS
    BEGIN
        IF P_ID_ARCHIVO_LADO_A IS NULL AND P_ID_ARCHIVO_LADO_B IS NULL
           AND P_MENSAJE_LADO_A IS NULL AND P_MENSAJE_LADO_B IS NULL THEN
            RAISE_APPLICATION_ERROR(-20402, 'Debe ingresar imagen o mensaje.');
        END IF;
        INSERT INTO PERSONALIZACION (
            ID_ARCHIVO_LADO_A, ID_ARCHIVO_LADO_B, MENSAJE_LADO_A,
            MENSAJE_LADO_B, CONFIG_LADO_A, CONFIG_LADO_B
        ) VALUES (
            P_ID_ARCHIVO_LADO_A, P_ID_ARCHIVO_LADO_B, P_MENSAJE_LADO_A,
            P_MENSAJE_LADO_B, P_CONFIG_LADO_A, P_CONFIG_LADO_B
        ) RETURNING ID_PERSONALIZACION INTO O_ID_PERSONALIZACION;
    END SP_CREAR_PERSONALIZACION;

    PROCEDURE SP_AGREGAR_PRODUCTO (
        P_ID_CARRITO IN CARRITO_DETALLE.ID_CARRITO%TYPE,
        P_ID_PRODUCTO IN CARRITO_DETALLE.ID_PRODUCTO%TYPE,
        P_ID_PERSONALIZACION IN CARRITO_DETALLE.ID_PERSONALIZACION%TYPE,
        P_CANTIDAD IN CARRITO_DETALLE.CANTIDAD%TYPE,
        P_PRECIO_PERSONALIZA IN CARRITO_DETALLE.PRECIO_PERSONALIZA%TYPE,
        O_ID_CARRITO_DETALLE OUT CARRITO_DETALLE.ID_CARRITO_DETALLE%TYPE
    ) AS
        V_SITIO_CARRITO CARRITO.ID_SITIO%TYPE;
        V_SITIO_PRODUCTO PRODUCTO.ID_SITIO%TYPE;
        V_PRECIO PRODUCTO.PRECIO_BASE%TYPE;
        V_ACTIVO PRODUCTO.ACTIVO%TYPE;
        V_BLOQUEADA PERSONALIZACION.BLOQUEADA%TYPE;
    BEGIN
        IF P_CANTIDAD <= 0 OR P_PRECIO_PERSONALIZA < 0 THEN
            RAISE_APPLICATION_ERROR(-20403, 'Cantidad o precio no valido.');
        END IF;
        SELECT ID_SITIO INTO V_SITIO_CARRITO FROM CARRITO
         WHERE ID_CARRITO = P_ID_CARRITO AND ESTADO = 'ABIERTO' FOR UPDATE;
        SELECT ID_SITIO, PRECIO_BASE, ACTIVO INTO V_SITIO_PRODUCTO, V_PRECIO, V_ACTIVO
          FROM PRODUCTO WHERE ID_PRODUCTO = P_ID_PRODUCTO;
        IF V_SITIO_CARRITO <> V_SITIO_PRODUCTO OR V_ACTIVO <> 'S' THEN
            RAISE_APPLICATION_ERROR(-20404, 'El producto no pertenece al sitio o esta inactivo.');
        END IF;
        IF P_ID_PERSONALIZACION IS NOT NULL THEN
            SELECT BLOQUEADA INTO V_BLOQUEADA FROM PERSONALIZACION
             WHERE ID_PERSONALIZACION = P_ID_PERSONALIZACION;
            IF V_BLOQUEADA = 'S' THEN RAISE_APPLICATION_ERROR(-20405, 'La personalizacion esta bloqueada.'); END IF;
        END IF;
        INSERT INTO CARRITO_DETALLE (
            ID_CARRITO, ID_PRODUCTO, ID_PERSONALIZACION,
            CANTIDAD, PRECIO_UNITARIO, PRECIO_PERSONALIZA
        ) VALUES (
            P_ID_CARRITO, P_ID_PRODUCTO, P_ID_PERSONALIZACION,
            P_CANTIDAD, V_PRECIO, P_PRECIO_PERSONALIZA
        ) RETURNING ID_CARRITO_DETALLE INTO O_ID_CARRITO_DETALLE;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20406, 'No existe el carrito, producto o personalizacion.');
    END SP_AGREGAR_PRODUCTO;

    PROCEDURE SP_ACTUALIZAR_CANTIDAD (
        P_ID_CARRITO_DETALLE IN CARRITO_DETALLE.ID_CARRITO_DETALLE%TYPE,
        P_CANTIDAD IN CARRITO_DETALLE.CANTIDAD%TYPE
    ) AS
    BEGIN
        IF P_CANTIDAD <= 0 THEN RAISE_APPLICATION_ERROR(-20407, 'La cantidad debe ser mayor que cero.'); END IF;
        UPDATE CARRITO_DETALLE CD SET CANTIDAD = P_CANTIDAD
         WHERE CD.ID_CARRITO_DETALLE = P_ID_CARRITO_DETALLE
           AND EXISTS (SELECT 1 FROM CARRITO C WHERE C.ID_CARRITO = CD.ID_CARRITO AND C.ESTADO = 'ABIERTO');
        IF SQL%ROWCOUNT = 0 THEN RAISE_APPLICATION_ERROR(-20408, 'El detalle no existe o el carrito esta cerrado.'); END IF;
    END SP_ACTUALIZAR_CANTIDAD;

    PROCEDURE SP_ELIMINAR_DETALLE (P_ID_CARRITO_DETALLE IN CARRITO_DETALLE.ID_CARRITO_DETALLE%TYPE) AS
    BEGIN
        DELETE FROM CARRITO_DETALLE CD
         WHERE CD.ID_CARRITO_DETALLE = P_ID_CARRITO_DETALLE
           AND EXISTS (SELECT 1 FROM CARRITO C WHERE C.ID_CARRITO = CD.ID_CARRITO AND C.ESTADO = 'ABIERTO');
        IF SQL%ROWCOUNT = 0 THEN RAISE_APPLICATION_ERROR(-20409, 'El detalle no existe o el carrito esta cerrado.'); END IF;
    END SP_ELIMINAR_DETALLE;

    PROCEDURE SP_OBTENER_CARRITO (P_ID_CARRITO IN CARRITO.ID_CARRITO%TYPE, O_DATOS OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN O_DATOS FOR
            SELECT C.ID_CARRITO, C.ID_USUARIO, C.ID_SITIO, C.ESTADO,
                   CD.ID_CARRITO_DETALLE, CD.ID_PRODUCTO, P.SKU,
                   P.NOMBRE PRODUCTO, CD.ID_PERSONALIZACION, CD.CANTIDAD,
                   CD.PRECIO_UNITARIO, CD.PRECIO_PERSONALIZA, CD.SUBTOTAL,
                   SUM(CD.SUBTOTAL) OVER (PARTITION BY C.ID_CARRITO) TOTAL_CARRITO
              FROM CARRITO C
              LEFT JOIN CARRITO_DETALLE CD ON CD.ID_CARRITO = C.ID_CARRITO
              LEFT JOIN PRODUCTO P ON P.ID_PRODUCTO = CD.ID_PRODUCTO
             WHERE C.ID_CARRITO = P_ID_CARRITO
             ORDER BY CD.FECHA_AGREGADO, CD.ID_CARRITO_DETALLE;
    END SP_OBTENER_CARRITO;

    PROCEDURE SP_ABANDONAR_CARRITO (P_ID_CARRITO IN CARRITO.ID_CARRITO%TYPE) AS
    BEGIN
        UPDATE CARRITO SET ESTADO = 'ABANDONADO'
         WHERE ID_CARRITO = P_ID_CARRITO AND ESTADO = 'ABIERTO';
        IF SQL%ROWCOUNT = 0 THEN RAISE_APPLICATION_ERROR(-20410, 'El carrito no existe o esta cerrado.'); END IF;
    END SP_ABANDONAR_CARRITO;
END PKG_CARRITO;
/
SHOW ERRORS PACKAGE BODY PKG_CARRITO;

CREATE OR REPLACE PACKAGE BODY PKG_PEDIDO AS
    PROCEDURE SP_CREAR_DESDE_CARRITO (
        P_ID_CARRITO IN CARRITO.ID_CARRITO%TYPE,
        P_ID_AREA_ENTREGA IN AREA_ENTREGA.ID_AREA_ENTREGA%TYPE,
        P_NUMERO_PEDIDO IN PEDIDO.NUMERO_PEDIDO%TYPE,
        P_TOKEN_QR_HASH IN PEDIDO.TOKEN_QR_HASH%TYPE,
        P_COD_MONEDA IN PEDIDO.COD_MONEDA%TYPE,
        P_REFERENCIA_ENTREGA IN PEDIDO.REFERENCIA_ENTREGA%TYPE,
        P_OBSERVACIONES IN PEDIDO.OBSERVACIONES%TYPE,
        O_ID_PEDIDO OUT PEDIDO.ID_PEDIDO%TYPE
    ) AS
        V_ID_USUARIO CARRITO.ID_USUARIO%TYPE;
        V_ID_SITIO CARRITO.ID_SITIO%TYPE;
        V_SITIO_AREA AREA_ENTREGA.ID_SITIO%TYPE;
        V_CARGO AREA_ENTREGA.CARGO_ENTREGA%TYPE;
        V_ID_ESTADO ESTADO_PEDIDO.ID_ESTADO_PEDIDO%TYPE;
        V_SUBTOTAL PEDIDO.SUBTOTAL%TYPE;
        V_LINEAS NUMBER;
    BEGIN
        SELECT ID_USUARIO, ID_SITIO INTO V_ID_USUARIO, V_ID_SITIO
          FROM CARRITO WHERE ID_CARRITO = P_ID_CARRITO AND ESTADO = 'ABIERTO' FOR UPDATE;
        SELECT ID_SITIO, CARGO_ENTREGA INTO V_SITIO_AREA, V_CARGO
          FROM AREA_ENTREGA WHERE ID_AREA_ENTREGA = P_ID_AREA_ENTREGA AND ACTIVO = 'S';
        IF V_ID_SITIO <> V_SITIO_AREA THEN
            RAISE_APPLICATION_ERROR(-20501, 'El area no pertenece al sitio del carrito.');
        END IF;
        SELECT COUNT(*), NVL(SUM(SUBTOTAL),0) INTO V_LINEAS, V_SUBTOTAL
          FROM CARRITO_DETALLE WHERE ID_CARRITO = P_ID_CARRITO;
        IF V_LINEAS = 0 THEN RAISE_APPLICATION_ERROR(-20502, 'El carrito no contiene productos.'); END IF;
        SELECT ID_ESTADO_PEDIDO INTO V_ID_ESTADO FROM ESTADO_PEDIDO
         WHERE CODIGO = 'GENERADO' AND ACTIVO = 'S';

        INSERT INTO PEDIDO (
            ID_CARRITO_ORIGEN, ID_USUARIO, ID_SITIO, ID_AREA_ENTREGA,
            ID_ESTADO_PEDIDO, NUMERO_PEDIDO, TOKEN_QR_HASH,
            SUBTOTAL, CARGO_ENTREGA, TOTAL, COD_MONEDA,
            REFERENCIA_ENTREGA, OBSERVACIONES
        ) VALUES (
            P_ID_CARRITO, V_ID_USUARIO, V_ID_SITIO, P_ID_AREA_ENTREGA,
            V_ID_ESTADO, TRIM(P_NUMERO_PEDIDO), P_TOKEN_QR_HASH,
            V_SUBTOTAL, V_CARGO, V_SUBTOTAL + V_CARGO, UPPER(P_COD_MONEDA),
            P_REFERENCIA_ENTREGA, P_OBSERVACIONES
        ) RETURNING ID_PEDIDO INTO O_ID_PEDIDO;

        INSERT INTO PEDIDO_DETALLE (
            ID_PEDIDO, ID_PRODUCTO, ID_PERSONALIZACION, NUMERO_LINEA,
            SKU_PRODUCTO, NOMBRE_PRODUCTO, CANTIDAD,
            PRECIO_UNITARIO, PRECIO_PERSONALIZA
        )
        SELECT O_ID_PEDIDO, CD.ID_PRODUCTO, CD.ID_PERSONALIZACION,
               ROW_NUMBER() OVER (ORDER BY CD.ID_CARRITO_DETALLE),
               P.SKU, P.NOMBRE, CD.CANTIDAD, CD.PRECIO_UNITARIO, CD.PRECIO_PERSONALIZA
          FROM CARRITO_DETALLE CD JOIN PRODUCTO P ON P.ID_PRODUCTO = CD.ID_PRODUCTO
         WHERE CD.ID_CARRITO = P_ID_CARRITO;

        INSERT INTO PEDIDO_ESTADO_HISTORIAL (
            ID_PEDIDO, ID_ESTADO_PEDIDO, ID_USUARIO_ACTOR, COMENTARIO
        ) VALUES (O_ID_PEDIDO, V_ID_ESTADO, V_ID_USUARIO, 'Pedido creado desde el carrito.');

        UPDATE PERSONALIZACION SET BLOQUEADA = 'S'
         WHERE ID_PERSONALIZACION IN (
             SELECT ID_PERSONALIZACION FROM CARRITO_DETALLE
              WHERE ID_CARRITO = P_ID_CARRITO AND ID_PERSONALIZACION IS NOT NULL
         );
        UPDATE CARRITO SET ESTADO = 'CONVERTIDO' WHERE ID_CARRITO = P_ID_CARRITO;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20503, 'El numero, token QR o carrito ya fue utilizado.');
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20504, 'No existe el carrito, area o estado requerido.');
    END SP_CREAR_DESDE_CARRITO;

    PROCEDURE SP_CAMBIAR_ESTADO (
        P_ID_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE,
        P_CODIGO_ESTADO IN ESTADO_PEDIDO.CODIGO%TYPE,
        P_ID_USUARIO_ACTOR IN PEDIDO_ESTADO_HISTORIAL.ID_USUARIO_ACTOR%TYPE,
        P_COMENTARIO IN PEDIDO_ESTADO_HISTORIAL.COMENTARIO%TYPE,
        P_DIRECCION_IP IN PEDIDO_ESTADO_HISTORIAL.DIRECCION_IP%TYPE
    ) AS
        V_ACTUAL PEDIDO.ID_ESTADO_PEDIDO%TYPE;
        V_FINAL ESTADO_PEDIDO.ES_FINAL%TYPE;
        V_NUEVO ESTADO_PEDIDO.ID_ESTADO_PEDIDO%TYPE;
    BEGIN
        SELECT P.ID_ESTADO_PEDIDO, E.ES_FINAL INTO V_ACTUAL, V_FINAL
          FROM PEDIDO P JOIN ESTADO_PEDIDO E ON E.ID_ESTADO_PEDIDO = P.ID_ESTADO_PEDIDO
         WHERE P.ID_PEDIDO = P_ID_PEDIDO FOR UPDATE OF P.ID_ESTADO_PEDIDO;
        SELECT ID_ESTADO_PEDIDO INTO V_NUEVO FROM ESTADO_PEDIDO
         WHERE CODIGO = UPPER(TRIM(P_CODIGO_ESTADO)) AND ACTIVO = 'S';
        IF V_ACTUAL = V_NUEVO THEN RETURN; END IF;
        IF V_FINAL = 'S' THEN RAISE_APPLICATION_ERROR(-20505, 'El pedido ya esta en estado final.'); END IF;
        UPDATE PEDIDO SET ID_ESTADO_PEDIDO = V_NUEVO WHERE ID_PEDIDO = P_ID_PEDIDO;
        INSERT INTO PEDIDO_ESTADO_HISTORIAL (
            ID_PEDIDO, ID_ESTADO_PEDIDO, ID_USUARIO_ACTOR, COMENTARIO, DIRECCION_IP
        ) VALUES (P_ID_PEDIDO, V_NUEVO, P_ID_USUARIO_ACTOR, P_COMENTARIO, P_DIRECCION_IP);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20506, 'El pedido o estado no existe.');
    END SP_CAMBIAR_ESTADO;

    PROCEDURE SP_OBTENER_RESUMEN (P_ID_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE, O_DATOS OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN O_DATOS FOR SELECT * FROM VW_PEDIDO_RESUMEN WHERE ID_PEDIDO = P_ID_PEDIDO;
    END SP_OBTENER_RESUMEN;

    PROCEDURE SP_OBTENER_DETALLE (P_ID_PEDIDO IN PEDIDO.ID_PEDIDO%TYPE, O_DATOS OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN O_DATOS FOR
            SELECT ID_PEDIDO_DETALLE, ID_PEDIDO, ID_PRODUCTO, ID_PERSONALIZACION,
                   NUMERO_LINEA, SKU_PRODUCTO, NOMBRE_PRODUCTO, CANTIDAD,
                   PRECIO_UNITARIO, PRECIO_PERSONALIZA, SUBTOTAL
              FROM PEDIDO_DETALLE WHERE ID_PEDIDO = P_ID_PEDIDO ORDER BY NUMERO_LINEA;
    END SP_OBTENER_DETALLE;

    PROCEDURE SP_LISTAR_POR_USUARIO (P_ID_USUARIO IN PEDIDO.ID_USUARIO%TYPE, O_DATOS OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN O_DATOS FOR
            SELECT * FROM VW_PEDIDO_RESUMEN
             WHERE ID_USUARIO = P_ID_USUARIO ORDER BY FECHA_PEDIDO DESC;
    END SP_LISTAR_POR_USUARIO;

    PROCEDURE SP_CONSULTAR_TRACKING (P_TOKEN_QR_HASH IN PEDIDO.TOKEN_QR_HASH%TYPE, O_DATOS OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN O_DATOS FOR
            SELECT T.* FROM VW_TRACKING_PEDIDO T
              JOIN PEDIDO P ON P.ID_PEDIDO = T.ID_PEDIDO
             WHERE P.TOKEN_QR_HASH = P_TOKEN_QR_HASH ORDER BY T.FECHA_ESTADO;
    END SP_CONSULTAR_TRACKING;
END PKG_PEDIDO;
/
SHOW ERRORS PACKAGE BODY PKG_PEDIDO;

CREATE OR REPLACE PACKAGE BODY PKG_PAGO_ENTREGA AS
    PROCEDURE SP_REGISTRAR_PAGO (
        P_ID_PEDIDO IN PAGO.ID_PEDIDO%TYPE,
        P_CODIGO_METODO IN METODO_PAGO.CODIGO%TYPE,
        P_CODIGO_ESTADO IN ESTADO_PAGO.CODIGO%TYPE,
        P_MONTO IN PAGO.MONTO%TYPE,
        P_PROVEEDOR_PAGO IN PAGO.PROVEEDOR_PAGO%TYPE,
        P_REFERENCIA_PROV IN PAGO.REFERENCIA_PROV%TYPE,
        P_MARCA_TARJETA IN PAGO.MARCA_TARJETA%TYPE,
        P_ULTIMOS_4 IN PAGO.ULTIMOS_4%TYPE,
        P_OBSERVACIONES IN PAGO.OBSERVACIONES%TYPE,
        O_ID_PAGO OUT PAGO.ID_PAGO%TYPE
    ) AS
        V_METODO METODO_PAGO.ID_METODO_PAGO%TYPE;
        V_REQUIERE METODO_PAGO.REQUIERE_PROVEEDOR%TYPE;
        V_ESTADO ESTADO_PAGO.ID_ESTADO_PAGO%TYPE;
        V_TOTAL PEDIDO.TOTAL%TYPE;
        V_MONEDA PEDIDO.COD_MONEDA%TYPE;
    BEGIN
        SELECT TOTAL, COD_MONEDA INTO V_TOTAL, V_MONEDA FROM PEDIDO WHERE ID_PEDIDO = P_ID_PEDIDO;
        IF P_MONTO <= 0 OR P_MONTO > V_TOTAL THEN
            RAISE_APPLICATION_ERROR(-20601, 'El monto no es valido para el pedido.');
        END IF;
        SELECT ID_METODO_PAGO, REQUIERE_PROVEEDOR INTO V_METODO, V_REQUIERE
          FROM METODO_PAGO WHERE CODIGO = UPPER(TRIM(P_CODIGO_METODO)) AND ACTIVO = 'S';
        IF V_REQUIERE = 'S' AND (P_PROVEEDOR_PAGO IS NULL OR P_REFERENCIA_PROV IS NULL) THEN
            RAISE_APPLICATION_ERROR(-20602, 'El metodo requiere proveedor y referencia.');
        END IF;
        SELECT ID_ESTADO_PAGO INTO V_ESTADO FROM ESTADO_PAGO
         WHERE CODIGO = UPPER(TRIM(P_CODIGO_ESTADO)) AND ACTIVO = 'S';
        INSERT INTO PAGO (
            ID_PEDIDO, ID_METODO_PAGO, ID_ESTADO_PAGO, MONTO, COD_MONEDA,
            PROVEEDOR_PAGO, REFERENCIA_PROV, MARCA_TARJETA, ULTIMOS_4,
            FECHA_CONFIRMACION, OBSERVACIONES
        ) VALUES (
            P_ID_PEDIDO, V_METODO, V_ESTADO, P_MONTO, V_MONEDA,
            P_PROVEEDOR_PAGO, P_REFERENCIA_PROV, P_MARCA_TARJETA, P_ULTIMOS_4,
            CASE WHEN UPPER(TRIM(P_CODIGO_ESTADO)) IN ('APROBADO','PAGADO_EFECTIVO')
                 THEN SYSTIMESTAMP END,
            P_OBSERVACIONES
        ) RETURNING ID_PAGO INTO O_ID_PAGO;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN RAISE_APPLICATION_ERROR(-20603, 'La referencia ya fue registrada.');
        WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20604, 'No existe el pedido, metodo o estado.');
    END SP_REGISTRAR_PAGO;

    PROCEDURE SP_CAMBIAR_ESTADO_PAGO (
        P_ID_PAGO IN PAGO.ID_PAGO%TYPE,
        P_CODIGO_ESTADO IN ESTADO_PAGO.CODIGO%TYPE,
        P_OBSERVACIONES IN PAGO.OBSERVACIONES%TYPE
    ) AS
        V_ESTADO ESTADO_PAGO.ID_ESTADO_PAGO%TYPE;
    BEGIN
        SELECT ID_ESTADO_PAGO INTO V_ESTADO FROM ESTADO_PAGO
         WHERE CODIGO = UPPER(TRIM(P_CODIGO_ESTADO)) AND ACTIVO = 'S';
        UPDATE PAGO
           SET ID_ESTADO_PAGO = V_ESTADO,
               FECHA_CONFIRMACION = CASE
                   WHEN UPPER(TRIM(P_CODIGO_ESTADO)) IN ('APROBADO','PAGADO_EFECTIVO')
                   THEN SYSTIMESTAMP ELSE FECHA_CONFIRMACION END,
               OBSERVACIONES = COALESCE(P_OBSERVACIONES, OBSERVACIONES)
         WHERE ID_PAGO = P_ID_PAGO;
        IF SQL%ROWCOUNT = 0 THEN RAISE_APPLICATION_ERROR(-20605, 'El pago no existe.'); END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20606, 'El estado de pago no existe.');
    END SP_CAMBIAR_ESTADO_PAGO;

    PROCEDURE SP_LISTAR_PAGOS_PEDIDO (P_ID_PEDIDO IN PAGO.ID_PEDIDO%TYPE, O_DATOS OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN O_DATOS FOR
            SELECT PG.ID_PAGO, PG.ID_PEDIDO, MP.CODIGO CODIGO_METODO,
                   MP.NOMBRE METODO_PAGO, EP.CODIGO CODIGO_ESTADO,
                   EP.NOMBRE ESTADO_PAGO, PG.MONTO, PG.COD_MONEDA,
                   PG.PROVEEDOR_PAGO, PG.REFERENCIA_PROV, PG.MARCA_TARJETA,
                   PG.ULTIMOS_4, PG.FECHA_REGISTRO, PG.FECHA_CONFIRMACION, PG.OBSERVACIONES
              FROM PAGO PG
              JOIN METODO_PAGO MP ON MP.ID_METODO_PAGO = PG.ID_METODO_PAGO
              JOIN ESTADO_PAGO EP ON EP.ID_ESTADO_PAGO = PG.ID_ESTADO_PAGO
             WHERE PG.ID_PEDIDO = P_ID_PEDIDO ORDER BY PG.FECHA_REGISTRO DESC;
    END SP_LISTAR_PAGOS_PEDIDO;

    PROCEDURE SP_ASIGNAR_ENTREGA (
        P_ID_PEDIDO IN ENTREGA.ID_PEDIDO%TYPE,
        P_ID_REPARTIDOR IN ENTREGA.ID_REPARTIDOR%TYPE,
        O_ID_ENTREGA OUT ENTREGA.ID_ENTREGA%TYPE
    ) AS
        V_AREA PEDIDO.ID_AREA_ENTREGA%TYPE;
        V_ESTADO ESTADO_ENTREGA.ID_ESTADO_ENTREGA%TYPE;
        V_INTENTO ENTREGA.NUMERO_INTENTO%TYPE;
        V_REPARTIDOR NUMBER;
    BEGIN
        SELECT ID_AREA_ENTREGA INTO V_AREA FROM PEDIDO WHERE ID_PEDIDO = P_ID_PEDIDO FOR UPDATE;
        SELECT COUNT(*) INTO V_REPARTIDOR
          FROM USUARIO U JOIN USUARIO_ROL UR ON UR.ID_USUARIO = U.ID_USUARIO
          JOIN ROL R ON R.ID_ROL = UR.ID_ROL
         WHERE U.ID_USUARIO = P_ID_REPARTIDOR AND U.ACTIVO = 'S' AND U.BLOQUEADO = 'N'
           AND R.CODIGO = 'REPARTIDOR' AND R.ACTIVO = 'S';
        IF V_REPARTIDOR = 0 THEN RAISE_APPLICATION_ERROR(-20607, 'El usuario no es repartidor activo.'); END IF;
        SELECT ID_ESTADO_ENTREGA INTO V_ESTADO FROM ESTADO_ENTREGA
         WHERE CODIGO = 'ASIGNADA' AND ACTIVO = 'S';
        SELECT NVL(MAX(NUMERO_INTENTO),0) + 1 INTO V_INTENTO FROM ENTREGA WHERE ID_PEDIDO = P_ID_PEDIDO;
        INSERT INTO ENTREGA (
            ID_PEDIDO, ID_REPARTIDOR, ID_ESTADO_ENTREGA,
            ID_AREA_ENTREGA, NUMERO_INTENTO, FECHA_ASIGNACION
        ) VALUES (
            P_ID_PEDIDO, P_ID_REPARTIDOR, V_ESTADO, V_AREA, V_INTENTO, SYSTIMESTAMP
        ) RETURNING ID_ENTREGA INTO O_ID_ENTREGA;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20608, 'No existe el pedido o estado ASIGNADA.');
    END SP_ASIGNAR_ENTREGA;

    PROCEDURE SP_REGISTRAR_RESULTADO_ENTREGA (
        P_ID_ENTREGA IN ENTREGA.ID_ENTREGA%TYPE,
        P_CODIGO_ESTADO IN ESTADO_ENTREGA.CODIGO%TYPE,
        P_ID_ARCHIVO_EVIDENCIA IN ENTREGA.ID_ARCHIVO_EVIDENCIA%TYPE,
        P_MONTO_EFECTIVO IN ENTREGA.MONTO_EFECTIVO%TYPE,
        P_OBSERVACIONES IN ENTREGA.OBSERVACIONES%TYPE,
        P_ID_USUARIO_ACTOR IN USUARIO.ID_USUARIO%TYPE
    ) AS
        V_ESTADO ESTADO_ENTREGA.ID_ESTADO_ENTREGA%TYPE;
        V_PEDIDO ENTREGA.ID_PEDIDO%TYPE;
        V_CODIGO ESTADO_ENTREGA.CODIGO%TYPE;
    BEGIN
        V_CODIGO := UPPER(TRIM(P_CODIGO_ESTADO));
        SELECT ID_PEDIDO INTO V_PEDIDO FROM ENTREGA WHERE ID_ENTREGA = P_ID_ENTREGA FOR UPDATE;
        SELECT ID_ESTADO_ENTREGA INTO V_ESTADO FROM ESTADO_ENTREGA
         WHERE CODIGO = V_CODIGO AND ACTIVO = 'S';
        UPDATE ENTREGA
           SET ID_ESTADO_ENTREGA = V_ESTADO,
               ID_ARCHIVO_EVIDENCIA = COALESCE(P_ID_ARCHIVO_EVIDENCIA, ID_ARCHIVO_EVIDENCIA),
               FECHA_INTENTO = SYSTIMESTAMP,
               FECHA_ENTREGA = CASE WHEN V_CODIGO = 'ENTREGADA' THEN SYSTIMESTAMP ELSE FECHA_ENTREGA END,
               MONTO_EFECTIVO = P_MONTO_EFECTIVO,
               OBSERVACIONES = P_OBSERVACIONES
         WHERE ID_ENTREGA = P_ID_ENTREGA;
        IF V_CODIGO = 'ENTREGADA' THEN
            PKG_PEDIDO.SP_CAMBIAR_ESTADO(V_PEDIDO, 'ENTREGADO', P_ID_USUARIO_ACTOR,
                COALESCE(P_OBSERVACIONES, 'Entrega completada.'), NULL);
        ELSIF V_CODIGO = 'NO_ENCONTRADO' THEN
            PKG_PEDIDO.SP_CAMBIAR_ESTADO(V_PEDIDO, 'COMPRADOR_NO_ENCONTRADO', P_ID_USUARIO_ACTOR,
                COALESCE(P_OBSERVACIONES, 'Comprador no encontrado.'), NULL);
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20609, 'No existe la entrega o estado.');
    END SP_REGISTRAR_RESULTADO_ENTREGA;

    PROCEDURE SP_LISTAR_ENTREGAS_REPARTIDOR (
        P_ID_REPARTIDOR IN ENTREGA.ID_REPARTIDOR%TYPE,
        O_DATOS OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN O_DATOS FOR
            SELECT E.ID_ENTREGA, E.ID_PEDIDO, P.NUMERO_PEDIDO, E.NUMERO_INTENTO,
                   EE.CODIGO CODIGO_ESTADO, EE.NOMBRE ESTADO_ENTREGA,
                   AE.NOMBRE AREA_ENTREGA, AE.REFERENCIA, E.FECHA_ASIGNACION,
                   E.FECHA_INTENTO, E.FECHA_ENTREGA, E.MONTO_EFECTIVO, E.OBSERVACIONES
              FROM ENTREGA E JOIN PEDIDO P ON P.ID_PEDIDO = E.ID_PEDIDO
              JOIN ESTADO_ENTREGA EE ON EE.ID_ESTADO_ENTREGA = E.ID_ESTADO_ENTREGA
              JOIN AREA_ENTREGA AE ON AE.ID_AREA_ENTREGA = E.ID_AREA_ENTREGA
             WHERE E.ID_REPARTIDOR = P_ID_REPARTIDOR
             ORDER BY E.FECHA_ASIGNACION DESC, E.ID_ENTREGA DESC;
    END SP_LISTAR_ENTREGAS_REPARTIDOR;
END PKG_PAGO_ENTREGA;
/
SHOW ERRORS PACKAGE BODY PKG_PAGO_ENTREGA;

-- ============================================================
-- 3. VALIDACION FINAL
-- ============================================================

DECLARE
    V_OBJETOS NUMBER;
    V_INVALIDOS NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_OBJETOS FROM USER_OBJECTS
     WHERE OBJECT_NAME IN (
        'PKG_SEGURIDAD','PKG_ARCHIVO','PKG_CATALOGO',
        'PKG_CARRITO','PKG_PEDIDO','PKG_PAGO_ENTREGA'
     ) AND OBJECT_TYPE IN ('PACKAGE','PACKAGE BODY');

    SELECT COUNT(*) INTO V_INVALIDOS FROM USER_OBJECTS
     WHERE OBJECT_NAME IN (
        'PKG_SEGURIDAD','PKG_ARCHIVO','PKG_CATALOGO',
        'PKG_CARRITO','PKG_PEDIDO','PKG_PAGO_ENTREGA'
     ) AND OBJECT_TYPE IN ('PACKAGE','PACKAGE BODY') AND STATUS <> 'VALID';

    DBMS_OUTPUT.PUT_LINE('Objetos esperados (spec + body): 12 / creados: ' || V_OBJETOS);
    DBMS_OUTPUT.PUT_LINE('Objetos invalidos: ' || V_INVALIDOS);
    IF V_OBJETOS <> 12 OR V_INVALIDOS <> 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Revise errores de compilacion en USER_ERRORS.');
    END IF;
    DBMS_OUTPUT.PUT_LINE('PACKAGES PL/SQL instalados correctamente.');
END;
/

SELECT NAME, TYPE, LINE, POSITION, TEXT
  FROM USER_ERRORS
 WHERE NAME IN (
    'PKG_SEGURIDAD','PKG_ARCHIVO','PKG_CATALOGO',
    'PKG_CARRITO','PKG_PEDIDO','PKG_PAGO_ENTREGA'
 )
 ORDER BY NAME, SEQUENCE;

-- ============================================================
-- INSTALACION DE PACKAGES FINALIZADA
-- ============================================================
