-- Alta de categorías desde Gestor de Productos. No modifica los paquetes existentes.
CREATE OR REPLACE PROCEDURE SP_CREAR_CATEGORIA_PRODUCTO (
    P_CODIGO IN CATEGORIA_PRODUCTO.CODIGO%TYPE,
    P_NOMBRE IN CATEGORIA_PRODUCTO.NOMBRE%TYPE,
    P_DESCRIPCION IN CATEGORIA_PRODUCTO.DESCRIPCION%TYPE,
    O_ID_CATEGORIA OUT CATEGORIA_PRODUCTO.ID_CATEGORIA%TYPE
) AS
BEGIN
    IF TRIM(P_CODIGO) IS NULL OR TRIM(P_NOMBRE) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20310, 'Código y nombre de categoría son obligatorios.');
    END IF;
    IF LENGTH(TRIM(P_CODIGO)) > 30 OR LENGTH(TRIM(P_NOMBRE)) > 100
       OR LENGTH(P_DESCRIPCION) > 300 THEN
        RAISE_APPLICATION_ERROR(-20311, 'Los datos de la categoría exceden la longitud permitida.');
    END IF;
    INSERT INTO CATEGORIA_PRODUCTO (CODIGO, NOMBRE, DESCRIPCION, ACTIVO)
    VALUES (UPPER(TRIM(P_CODIGO)), TRIM(P_NOMBRE), P_DESCRIPCION, 'S')
    RETURNING ID_CATEGORIA INTO O_ID_CATEGORIA;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20312, 'Ya existe una categoría con ese código.');
END SP_CREAR_CATEGORIA_PRODUCTO;
/
SHOW ERRORS PROCEDURE SP_CREAR_CATEGORIA_PRODUCTO;
