CREATE OR REPLACE PACKAGE PKG_COMPRA AS
 FUNCTION ES_ADMIN(P_ACTOR NUMBER) RETURN NUMBER;
 FUNCTION PUEDE_VER(P_PEDIDO NUMBER,P_ACTOR NUMBER,P_VISTA VARCHAR2) RETURN NUMBER;
 PROCEDURE CREAR(P_ACTOR NUMBER,P_CARRITO NUMBER,P_MODALIDAD NUMBER,P_TELEFONO VARCHAR2,P_ALTERNO VARCHAR2,P_DEPARTAMENTO VARCHAR2,P_MUNICIPIO VARCHAR2,P_DIRECCION VARCHAR2,P_REFERENCIA VARCHAR2,P_METODO VARCHAR2,P_ENTORNO VARCHAR2,O_PEDIDO OUT NUMBER);
 PROCEDURE AVANZAR(P_PEDIDO NUMBER,P_ACTOR NUMBER,P_ESTADO VARCHAR2,P_COMENTARIO VARCHAR2);
 PROCEDURE ASIGNAR(P_PEDIDO NUMBER,P_ACTOR NUMBER,P_REPARTIDOR NUMBER);
 PROCEDURE FINALIZAR(P_PEDIDO NUMBER,P_ACTOR NUMBER,P_RESULTADO VARCHAR2,P_RECEPTOR VARCHAR2,P_EVIDENCIA NUMBER,P_EFECTIVO NUMBER,P_COMENTARIO VARCHAR2);
 PROCEDURE CORREGIR(P_PEDIDO NUMBER,P_ACTOR NUMBER,P_TELEFONO VARCHAR2,P_ALTERNO VARCHAR2,P_DEPARTAMENTO VARCHAR2,P_MUNICIPIO VARCHAR2,P_DIRECCION VARCHAR2,P_REFERENCIA VARCHAR2,P_MOTIVO VARCHAR2);
 PROCEDURE CONFIRMAR_PAGO(P_CHECKOUT VARCHAR2,P_ENTORNO VARCHAR2,P_EVENTO VARCHAR2,P_TIPO VARCHAR2,P_ESTADO VARCHAR2,P_MONTO NUMBER,P_MONEDA VARCHAR2,P_REFERENCIA VARCHAR2);
END PKG_COMPRA;
/
CREATE OR REPLACE PACKAGE BODY PKG_COMPRA AS
 FUNCTION ES_ADMIN(P_ACTOR NUMBER) RETURN NUMBER IS N NUMBER;
 BEGIN
 SELECT COUNT(*) INTO N FROM USUARIO U JOIN USUARIO_ROL UR ON UR.ID_USUARIO=U.ID_USUARIO JOIN ROL R ON R.ID_ROL=UR.ID_ROL
 WHERE U.ID_USUARIO=P_ACTOR AND U.ACTIVO='S' AND U.BLOQUEADO='N' AND R.ACTIVO='S' AND R.CODIGO IN ('ADMIN','SUPERVISOR');
 RETURN CASE WHEN N>0 THEN 1 ELSE 0 END;
 END;
 FUNCTION PUEDE_VER(P_PEDIDO NUMBER,P_ACTOR NUMBER,P_VISTA VARCHAR2) RETURN NUMBER IS N NUMBER;
 BEGIN
 SELECT COUNT(*) INTO N FROM PEDIDO P JOIN USUARIO U ON U.ID_USUARIO=P_ACTOR AND U.ACTIVO='S' AND U.BLOQUEADO='N'
 WHERE P.ID_PEDIDO=P_PEDIDO AND (
 (P_VISTA='cliente' AND P.ID_USUARIO=P_ACTOR) OR
 (P_VISTA='admin' AND ES_ADMIN(P_ACTOR)=1) OR
 (P_VISTA='repartidor' AND EXISTS(SELECT 1 FROM ENTREGA E WHERE E.ID_PEDIDO=P.ID_PEDIDO AND E.ID_REPARTIDOR=P_ACTOR)));
 RETURN CASE WHEN N>0 THEN 1 ELSE 0 END;
 END;
 PROCEDURE EXIGIR_ADMIN(P_ACTOR NUMBER) IS BEGIN
 IF ES_ADMIN(P_ACTOR)=0 THEN RAISE_APPLICATION_ERROR(-20703,'No tienes permiso para administrar pedidos.'); END IF;
 END;
 PROCEDURE HISTORIA(P_PEDIDO NUMBER,P_ACTOR NUMBER,P_ESTADO VARCHAR2,P_COMENTARIO VARCHAR2) IS E NUMBER;
 BEGIN
 SELECT ID_ESTADO_PEDIDO INTO E FROM ESTADO_PEDIDO WHERE CODIGO=P_ESTADO AND ACTIVO='S';
 UPDATE PEDIDO SET ID_ESTADO_PEDIDO=E,FECHA_MODIFICACION=SYSTIMESTAMP WHERE ID_PEDIDO=P_PEDIDO;
 INSERT INTO PEDIDO_ESTADO_HISTORIAL(ID_PEDIDO,ID_ESTADO_PEDIDO,ID_USUARIO_ACTOR,COMENTARIO) VALUES(P_PEDIDO,E,P_ACTOR,P_COMENTARIO);
 END;
 PROCEDURE CREAR(P_ACTOR NUMBER,P_CARRITO NUMBER,P_MODALIDAD NUMBER,P_TELEFONO VARCHAR2,P_ALTERNO VARCHAR2,P_DEPARTAMENTO VARCHAR2,P_MUNICIPIO VARCHAR2,P_DIRECCION VARCHAR2,P_REFERENCIA VARCHAR2,P_METODO VARCHAR2,P_ENTORNO VARCHAR2,O_PEDIDO OUT NUMBER) IS
 U NUMBER; S NUMBER; A NUMBER; M NUMBER; E NUMBER; N NUMBER; EST VARCHAR2(30); TOTAL_PED NUMBER;
 BEGIN
 IF P_MODALIDAD IS NULL OR P_MODALIDAD NOT IN (1,2) OR P_METODO IS NULL OR P_METODO NOT IN ('EFECTIVO','TARJETA') OR P_ENTORNO IS NULL OR P_ENTORNO NOT IN ('TEST','LIVE') THEN RAISE_APPLICATION_ERROR(-20700,'Modalidad o método inválido.'); END IF;
 IF TRIM(P_TELEFONO) IS NULL OR LENGTH(P_TELEFONO)>25 OR LENGTH(P_ALTERNO)>25 OR LENGTH(P_REFERENCIA)>300 THEN RAISE_APPLICATION_ERROR(-20700,'Revisa el teléfono y las referencias.'); END IF;
 IF P_MODALIDAD=2 AND (TRIM(P_DEPARTAMENTO) IS NULL OR TRIM(P_MUNICIPIO) IS NULL OR TRIM(P_DIRECCION) IS NULL) THEN RAISE_APPLICATION_ERROR(-20700,'Completa la dirección del domicilio.'); END IF;
 SELECT ID_USUARIO,ID_SITIO,ESTADO INTO U,S,EST FROM CARRITO WHERE ID_CARRITO=P_CARRITO FOR UPDATE;
 IF U<>P_ACTOR THEN RAISE_APPLICATION_ERROR(-20703,'El carrito no te pertenece.'); END IF;
 SELECT COUNT(*) INTO N FROM USUARIO WHERE ID_USUARIO=P_ACTOR AND ACTIVO='S' AND BLOQUEADO='N';
 IF N=0 THEN RAISE_APPLICATION_ERROR(-20703,'Usuario no disponible.'); END IF;
 -- Una repetición del checkout devuelve la misma compra, sin convertir dos veces el carrito.
 IF EST='CONVERTIDO' THEN SELECT ID_PEDIDO INTO O_PEDIDO FROM PEDIDO WHERE ID_CARRITO_ORIGEN=P_CARRITO; RETURN; END IF;
 IF EST<>'ABIERTO' THEN RAISE_APPLICATION_ERROR(-20709,'El carrito no está abierto.'); END IF;
 SELECT COUNT(*) INTO N FROM CARRITO_DETALLE CD JOIN PRODUCTO P ON P.ID_PRODUCTO=CD.ID_PRODUCTO WHERE CD.ID_CARRITO=P_CARRITO AND (P.ACTIVO<>'S' OR P.ID_SITIO<>S);
 IF N>0 THEN RAISE_APPLICATION_ERROR(-20709,'Un producto ya no está disponible. Actualiza el carrito.'); END IF;
 SELECT ID_AREA_ENTREGA INTO A FROM AREA_ENTREGA WHERE ID_SITIO=S AND CODIGO=CASE P_MODALIDAD WHEN 1 THEN 'FK_TIENDA' ELSE 'FK_DOMICILIO' END AND ACTIVO='S';
 PKG_PEDIDO.SP_CREAR_DESDE_CARRITO(P_CARRITO,A,'FK-'||SUBSTR(RAWTOHEX(SYS_GUID()),1,20),LOWER(RAWTOHEX(SYS_GUID())),'GTQ',P_REFERENCIA,NULL,O_PEDIDO);
 UPDATE PEDIDO SET ID_MODALIDAD_ENTREGA=P_MODALIDAD,TELEFONO_CONTACTO=TRIM(P_TELEFONO),TELEFONO_ALTERNO=TRIM(P_ALTERNO),
 DEPARTAMENTO=CASE WHEN P_MODALIDAD=2 THEN TRIM(P_DEPARTAMENTO) END,MUNICIPIO=CASE WHEN P_MODALIDAD=2 THEN TRIM(P_MUNICIPIO) END,
 DIRECCION_ENTREGA=CASE WHEN P_MODALIDAD=2 THEN TRIM(P_DIRECCION) END,
 CARGO_ENTREGA=CASE P_MODALIDAD WHEN 1 THEN 0 ELSE 25 END,TOTAL=SUBTOTAL+CASE P_MODALIDAD WHEN 1 THEN 0 ELSE 25 END WHERE ID_PEDIDO=O_PEDIDO RETURNING TOTAL INTO TOTAL_PED;
 IF TOTAL_PED<=0 THEN RAISE_APPLICATION_ERROR(-20700,'El total del pedido debe ser mayor a cero.'); END IF;
 SELECT ID_METODO_PAGO INTO M FROM METODO_PAGO WHERE CODIGO=P_METODO AND ACTIVO='S';
 SELECT ID_ESTADO_PAGO INTO E FROM ESTADO_PAGO WHERE CODIGO='PENDIENTE';
 INSERT INTO PAGO(ID_PEDIDO,ID_METODO_PAGO,ID_ESTADO_PAGO,MONTO,COD_MONEDA,PROVEEDOR_PAGO,ENTORNO,OBSERVACIONES)
 VALUES(O_PEDIDO,M,E,TOTAL_PED,'GTQ',CASE WHEN P_METODO='TARJETA' THEN 'RECURRENTE' END,P_ENTORNO,'Pago iniciado con el pedido.');
 END;
 PROCEDURE AVANZAR(P_PEDIDO NUMBER,P_ACTOR NUMBER,P_ESTADO VARCHAR2,P_COMENTARIO VARCHAR2) IS
 ACTUAL VARCHAR2(35); MODAL NUMBER; N NUMBER; PAGO_EST VARCHAR2(30); METODO VARCHAR2(20);
 BEGIN
 SELECT E.CODIGO,P.ID_MODALIDAD_ENTREGA INTO ACTUAL,MODAL FROM PEDIDO P JOIN ESTADO_PEDIDO E ON E.ID_ESTADO_PEDIDO=P.ID_ESTADO_PEDIDO WHERE P.ID_PEDIDO=P_PEDIDO FOR UPDATE OF P.ID_ESTADO_PEDIDO;
 IF P_ESTADO='EN_RUTA' THEN
 SELECT COUNT(*) INTO N FROM ENTREGA E JOIN ESTADO_ENTREGA EE ON EE.ID_ESTADO_ENTREGA=E.ID_ESTADO_ENTREGA WHERE E.ID_PEDIDO=P_PEDIDO AND E.ID_REPARTIDOR=P_ACTOR AND EE.CODIGO='ASIGNADA';
 IF N<>1 OR ACTUAL<>'LISTO_ENTREGA' THEN RAISE_APPLICATION_ERROR(-20709,'Necesitas una entrega asignada lista para salir.'); END IF;
 UPDATE ENTREGA SET ID_ESTADO_ENTREGA=(SELECT ID_ESTADO_ENTREGA FROM ESTADO_ENTREGA WHERE CODIGO='EN_RUTA') WHERE ID_PEDIDO=P_PEDIDO AND ID_REPARTIDOR=P_ACTOR AND ID_ESTADO_ENTREGA=(SELECT ID_ESTADO_ENTREGA FROM ESTADO_ENTREGA WHERE CODIGO='ASIGNADA');
 ELSE
 EXIGIR_ADMIN(P_ACTOR);
 SELECT EP.CODIGO,M.CODIGO INTO PAGO_EST,METODO FROM PAGO PG JOIN ESTADO_PAGO EP ON EP.ID_ESTADO_PAGO=PG.ID_ESTADO_PAGO JOIN METODO_PAGO M ON M.ID_METODO_PAGO=PG.ID_METODO_PAGO WHERE PG.ID_PEDIDO=P_PEDIDO ORDER BY PG.ID_PAGO DESC FETCH FIRST 1 ROW ONLY;
 IF P_ESTADO='EN_ELABORACION' THEN
 IF ACTUAL NOT IN ('GENERADO','PAGO_CONFIRMADO','PAGO_PENDIENTE') THEN RAISE_APPLICATION_ERROR(-20709,'El pedido no puede iniciar preparación desde su estado actual.'); END IF;
 IF METODO='TARJETA' AND PAGO_EST<>'APROBADO' THEN RAISE_APPLICATION_ERROR(-20709,'Primero debe confirmarse el pago con tarjeta.'); END IF;
 ELSIF P_ESTADO IN ('LISTO_ENTREGA','LISTO_RECOGER') THEN
 IF ACTUAL<>'EN_ELABORACION' OR (MODAL=1 AND P_ESTADO<>'LISTO_RECOGER') OR (MODAL=2 AND P_ESTADO<>'LISTO_ENTREGA') THEN RAISE_APPLICATION_ERROR(-20709,'La modalidad o el estado no permite esta acción.'); END IF;
 ELSIF P_ESTADO='CANCELADO' THEN
 IF ACTUAL IN ('ENTREGADO','RECOGIDO','CANCELADO') OR TRIM(P_COMENTARIO) IS NULL THEN RAISE_APPLICATION_ERROR(-20709,'No se puede cancelar o falta indicar el motivo.'); END IF;
 UPDATE PAGO SET ID_ESTADO_PAGO=(SELECT ID_ESTADO_PAGO FROM ESTADO_PAGO WHERE CODIGO=CASE WHEN PAGO_EST='APROBADO' THEN 'REEMBOLSO_PENDIENTE' ELSE 'ANULADO' END),OBSERVACIONES='Cancelación: '||SUBSTR(P_COMENTARIO,1,450) WHERE ID_PEDIDO=P_PEDIDO;
 UPDATE ENTREGA SET ID_ESTADO_ENTREGA=(SELECT ID_ESTADO_ENTREGA FROM ESTADO_ENTREGA WHERE CODIGO='CANCELADA') WHERE ID_PEDIDO=P_PEDIDO AND ID_ESTADO_ENTREGA IN (SELECT ID_ESTADO_ENTREGA FROM ESTADO_ENTREGA WHERE CODIGO IN ('PENDIENTE','ASIGNADA','EN_RUTA'));
 ELSIF P_ESTADO='NOTA' THEN
 IF TRIM(P_COMENTARIO) IS NULL THEN RAISE_APPLICATION_ERROR(-20700,'Escribe la observación.'); END IF;
 INSERT INTO PEDIDO_DATO_HISTORIAL(ID_PEDIDO,ID_USUARIO_ACTOR,MOTIVO,DATOS_ANTERIORES,DATOS_NUEVOS) VALUES(P_PEDIDO,P_ACTOR,P_COMENTARIO,'{}','{}'); RETURN;
 ELSE RAISE_APPLICATION_ERROR(-20709,'Transición no permitida.');
 END IF;
 END IF;
 HISTORIA(P_PEDIDO,P_ACTOR,P_ESTADO,SUBSTR(P_COMENTARIO,1,500));
 END;
 PROCEDURE ASIGNAR(P_PEDIDO NUMBER,P_ACTOR NUMBER,P_REPARTIDOR NUMBER) IS EST VARCHAR2(35); MODAL NUMBER; N NUMBER; ID_N NUMBER;
 BEGIN
 EXIGIR_ADMIN(P_ACTOR);
 SELECT E.CODIGO,P.ID_MODALIDAD_ENTREGA INTO EST,MODAL FROM PEDIDO P JOIN ESTADO_PEDIDO E ON E.ID_ESTADO_PEDIDO=P.ID_ESTADO_PEDIDO WHERE P.ID_PEDIDO=P_PEDIDO FOR UPDATE OF P.ID_ESTADO_PEDIDO;
 IF MODAL<>2 OR EST NOT IN ('LISTO_ENTREGA','COMPRADOR_NO_ENCONTRADO') THEN RAISE_APPLICATION_ERROR(-20709,'El pedido no está listo para asignar.'); END IF;
 SELECT COUNT(*) INTO N FROM ENTREGA E JOIN ESTADO_ENTREGA EE ON EE.ID_ESTADO_ENTREGA=E.ID_ESTADO_ENTREGA WHERE E.ID_PEDIDO=P_PEDIDO AND EE.CODIGO IN ('ASIGNADA','EN_RUTA');
 IF N>0 THEN RAISE_APPLICATION_ERROR(-20709,'El pedido ya tiene una entrega activa.'); END IF;
 PKG_PAGO_ENTREGA.SP_ASIGNAR_ENTREGA(P_PEDIDO,P_REPARTIDOR,ID_N);
 HISTORIA(P_PEDIDO,P_ACTOR,'LISTO_ENTREGA',CASE WHEN EST='COMPRADOR_NO_ENCONTRADO' THEN 'Entrega reprogramada y asignada.' ELSE 'Entrega asignada al mensajero.' END);
 END;
 PROCEDURE FINALIZAR(P_PEDIDO NUMBER,P_ACTOR NUMBER,P_RESULTADO VARCHAR2,P_RECEPTOR VARCHAR2,P_EVIDENCIA NUMBER,P_EFECTIVO NUMBER,P_COMENTARIO VARCHAR2) IS
 EST VARCHAR2(35); MODAL NUMBER; AREA NUMBER; ID_E NUMBER; EST_E NUMBER; MONTO NUMBER; METODO VARCHAR2(20); PAGO_EST VARCHAR2(30); N NUMBER; INTENTO NUMBER;
 BEGIN
 SELECT E.CODIGO,P.ID_MODALIDAD_ENTREGA,P.ID_AREA_ENTREGA,P.TOTAL INTO EST,MODAL,AREA,MONTO FROM PEDIDO P JOIN ESTADO_PEDIDO E ON E.ID_ESTADO_PEDIDO=P.ID_ESTADO_PEDIDO WHERE P.ID_PEDIDO=P_PEDIDO FOR UPDATE OF P.ID_ESTADO_PEDIDO;
 IF P_RESULTADO IS NULL OR P_RESULTADO NOT IN ('ENTREGADO','RECOGIDO','COMPRADOR_NO_ENCONTRADO') THEN RAISE_APPLICATION_ERROR(-20700,'Resultado inválido.'); END IF;
 IF MODAL=1 THEN
 EXIGIR_ADMIN(P_ACTOR);
 IF EST<>'LISTO_RECOGER' OR P_RESULTADO<>'RECOGIDO' THEN RAISE_APPLICATION_ERROR(-20709,'El pedido no está listo para recoger.'); END IF;
 SELECT NVL(MAX(NUMERO_INTENTO),0)+1 INTO INTENTO FROM ENTREGA WHERE ID_PEDIDO=P_PEDIDO;
 INSERT INTO ENTREGA(ID_PEDIDO,ID_AREA_ENTREGA,ID_ESTADO_ENTREGA,NUMERO_INTENTO,FECHA_ASIGNACION) VALUES(P_PEDIDO,AREA,(SELECT ID_ESTADO_ENTREGA FROM ESTADO_ENTREGA WHERE CODIGO='PENDIENTE'),INTENTO,SYSTIMESTAMP) RETURNING ID_ENTREGA INTO ID_E;
 ELSE
 IF EST<>'EN_RUTA' OR P_RESULTADO='RECOGIDO' THEN RAISE_APPLICATION_ERROR(-20709,'La entrega debe estar en ruta.'); END IF;
 SELECT E.ID_ENTREGA INTO ID_E FROM ENTREGA E JOIN ESTADO_ENTREGA EE ON EE.ID_ESTADO_ENTREGA=E.ID_ESTADO_ENTREGA WHERE E.ID_PEDIDO=P_PEDIDO AND E.ID_REPARTIDOR=P_ACTOR AND EE.CODIGO='EN_RUTA';
 END IF;
 IF P_RESULTADO='COMPRADOR_NO_ENCONTRADO' THEN
 IF TRIM(P_COMENTARIO) IS NULL THEN RAISE_APPLICATION_ERROR(-20700,'Indica el motivo del intento fallido.'); END IF;
 IF NVL(P_EFECTIVO,0)<>0 THEN RAISE_APPLICATION_ERROR(-20700,'Un intento fallido no registra cobro.'); END IF;
 ELSE
 IF TRIM(P_RECEPTOR) IS NULL THEN RAISE_APPLICATION_ERROR(-20700,'Indica quién recibió.'); END IF;
 IF MODAL=2 AND P_EVIDENCIA IS NULL THEN RAISE_APPLICATION_ERROR(-20700,'Adjunta la foto de evidencia.'); END IF;
 SELECT EP.CODIGO,M.CODIGO INTO PAGO_EST,METODO FROM PAGO PG JOIN ESTADO_PAGO EP ON EP.ID_ESTADO_PAGO=PG.ID_ESTADO_PAGO JOIN METODO_PAGO M ON M.ID_METODO_PAGO=PG.ID_METODO_PAGO WHERE PG.ID_PEDIDO=P_PEDIDO ORDER BY PG.ID_PAGO DESC FETCH FIRST 1 ROW ONLY;
 IF METODO='EFECTIVO' THEN
 IF P_EFECTIVO IS NULL OR P_EFECTIVO<>MONTO THEN RAISE_APPLICATION_ERROR(-20700,'El efectivo recibido debe coincidir con el total.'); END IF;
 UPDATE PAGO SET ID_ESTADO_PAGO=(SELECT ID_ESTADO_PAGO FROM ESTADO_PAGO WHERE CODIGO='PAGADO_EFECTIVO'),FECHA_CONFIRMACION=SYSTIMESTAMP,OBSERVACIONES='Cobro confirmado al entregar o recoger.' WHERE ID_PEDIDO=P_PEDIDO;
 ELSE
 IF PAGO_EST<>'APROBADO' OR NVL(P_EFECTIVO,0)<>0 THEN RAISE_APPLICATION_ERROR(-20709,'Verifica el pago con tarjeta; no corresponde cobrar efectivo.'); END IF;
 END IF;
 END IF;
 IF P_EVIDENCIA IS NOT NULL THEN
 SELECT COUNT(*) INTO N FROM ARCHIVO WHERE ID_ARCHIVO=P_EVIDENCIA AND TIPO_ARCHIVO='EVIDENCIA_ENTREGA' AND ID_USUARIO_CARGA=P_ACTOR AND ACTIVO='S';
 IF N=0 THEN RAISE_APPLICATION_ERROR(-20703,'La evidencia no te pertenece.'); END IF;
 END IF;
 SELECT ID_ESTADO_ENTREGA INTO EST_E FROM ESTADO_ENTREGA WHERE CODIGO=CASE P_RESULTADO WHEN 'ENTREGADO' THEN 'ENTREGADA' WHEN 'RECOGIDO' THEN 'RECOGIDA' ELSE 'NO_ENCONTRADO' END;
 UPDATE ENTREGA SET ID_ESTADO_ENTREGA=EST_E,NOMBRE_RECEPTOR=TRIM(P_RECEPTOR),ID_ARCHIVO_EVIDENCIA=P_EVIDENCIA,MONTO_EFECTIVO=NVL(P_EFECTIVO,0),OBSERVACIONES=P_COMENTARIO,FECHA_INTENTO=SYSTIMESTAMP,FECHA_ENTREGA=CASE WHEN P_RESULTADO<>'COMPRADOR_NO_ENCONTRADO' THEN SYSTIMESTAMP END WHERE ID_ENTREGA=ID_E;
 HISTORIA(P_PEDIDO,P_ACTOR,P_RESULTADO,CASE WHEN P_RESULTADO='COMPRADOR_NO_ENCONTRADO' THEN SUBSTR(P_COMENTARIO,1,500) ELSE 'Recepción registrada por el encargado.' END);
 END;
 PROCEDURE CORREGIR(P_PEDIDO NUMBER,P_ACTOR NUMBER,P_TELEFONO VARCHAR2,P_ALTERNO VARCHAR2,P_DEPARTAMENTO VARCHAR2,P_MUNICIPIO VARCHAR2,P_DIRECCION VARCHAR2,P_REFERENCIA VARCHAR2,P_MOTIVO VARCHAR2) IS EST VARCHAR2(35); MODAL NUMBER; ANTES CLOB; DESPUES CLOB;
 BEGIN
 EXIGIR_ADMIN(P_ACTOR);
 SELECT E.CODIGO,P.ID_MODALIDAD_ENTREGA INTO EST,MODAL FROM PEDIDO P JOIN ESTADO_PEDIDO E ON E.ID_ESTADO_PEDIDO=P.ID_ESTADO_PEDIDO WHERE P.ID_PEDIDO=P_PEDIDO FOR UPDATE OF P.ID_ESTADO_PEDIDO;
 IF EST IN ('ENTREGADO','RECOGIDO','CANCELADO','EN_RUTA') THEN RAISE_APPLICATION_ERROR(-20709,'No se pueden corregir datos en este estado.'); END IF;
 IF TRIM(P_MOTIVO) IS NULL OR TRIM(P_TELEFONO) IS NULL THEN RAISE_APPLICATION_ERROR(-20700,'Indica teléfono y motivo de la corrección.'); END IF;
 IF MODAL=2 AND (TRIM(P_DEPARTAMENTO) IS NULL OR TRIM(P_MUNICIPIO) IS NULL OR TRIM(P_DIRECCION) IS NULL) THEN RAISE_APPLICATION_ERROR(-20700,'Completa la dirección.'); END IF;
 SELECT JSON_OBJECT('telefono' VALUE TELEFONO_CONTACTO,'alterno' VALUE TELEFONO_ALTERNO,'departamento' VALUE DEPARTAMENTO,'municipio' VALUE MUNICIPIO,'direccion' VALUE DIRECCION_ENTREGA,'referencia' VALUE REFERENCIA_ENTREGA RETURNING CLOB) INTO ANTES FROM PEDIDO WHERE ID_PEDIDO=P_PEDIDO;
 UPDATE PEDIDO SET TELEFONO_CONTACTO=TRIM(P_TELEFONO),TELEFONO_ALTERNO=TRIM(P_ALTERNO),DEPARTAMENTO=CASE WHEN MODAL=2 THEN TRIM(P_DEPARTAMENTO) END,MUNICIPIO=CASE WHEN MODAL=2 THEN TRIM(P_MUNICIPIO) END,DIRECCION_ENTREGA=CASE WHEN MODAL=2 THEN TRIM(P_DIRECCION) END,REFERENCIA_ENTREGA=TRIM(P_REFERENCIA),FECHA_MODIFICACION=SYSTIMESTAMP WHERE ID_PEDIDO=P_PEDIDO;
 SELECT JSON_OBJECT('telefono' VALUE TELEFONO_CONTACTO,'alterno' VALUE TELEFONO_ALTERNO,'departamento' VALUE DEPARTAMENTO,'municipio' VALUE MUNICIPIO,'direccion' VALUE DIRECCION_ENTREGA,'referencia' VALUE REFERENCIA_ENTREGA RETURNING CLOB) INTO DESPUES FROM PEDIDO WHERE ID_PEDIDO=P_PEDIDO;
 INSERT INTO PEDIDO_DATO_HISTORIAL(ID_PEDIDO,ID_USUARIO_ACTOR,MOTIVO,DATOS_ANTERIORES,DATOS_NUEVOS) VALUES(P_PEDIDO,P_ACTOR,P_MOTIVO,ANTES,DESPUES);
 END;
 PROCEDURE CONFIRMAR_PAGO(P_CHECKOUT VARCHAR2,P_ENTORNO VARCHAR2,P_EVENTO VARCHAR2,P_TIPO VARCHAR2,P_ESTADO VARCHAR2,P_MONTO NUMBER,P_MONEDA VARCHAR2,P_REFERENCIA VARCHAR2) IS
 ID_P NUMBER; PED NUMBER; ACTUAL VARCHAR2(30); PED_EST VARCHAR2(35); N NUMBER; IMPORTE NUMBER; MONEDA CHAR(3); NUEVO VARCHAR2(30); EST_ID NUMBER;
 BEGIN
 SELECT ID_PEDIDO INTO PED FROM PAGO WHERE PROVEEDOR_PAGO='RECURRENTE' AND ENTORNO=P_ENTORNO AND ID_CHECKOUT_PROVEEDOR=P_CHECKOUT;
 SELECT E.CODIGO INTO PED_EST FROM PEDIDO P JOIN ESTADO_PEDIDO E ON E.ID_ESTADO_PEDIDO=P.ID_ESTADO_PEDIDO WHERE P.ID_PEDIDO=PED FOR UPDATE OF P.ID_ESTADO_PEDIDO;
 SELECT PG.ID_PAGO,EP.CODIGO,PG.MONTO,PG.COD_MONEDA INTO ID_P,ACTUAL,IMPORTE,MONEDA FROM PAGO PG JOIN ESTADO_PAGO EP ON EP.ID_ESTADO_PAGO=PG.ID_ESTADO_PAGO WHERE PG.PROVEEDOR_PAGO='RECURRENTE' AND PG.ENTORNO=P_ENTORNO AND PG.ID_CHECKOUT_PROVEEDOR=P_CHECKOUT FOR UPDATE OF PG.ID_ESTADO_PAGO;
 SELECT COUNT(*) INTO N FROM PAGO_EVENTO_PROVEEDOR WHERE PROVEEDOR='RECURRENTE' AND ENTORNO=P_ENTORNO AND ID_EVENTO_PROVEEDOR=P_EVENTO;
 IF N>0 THEN RETURN; END IF;
 IF P_MONTO IS NULL OR P_MONTO<>IMPORTE OR P_MONEDA IS NULL OR P_MONEDA<>MONEDA THEN RAISE_APPLICATION_ERROR(-20709,'Monto o moneda del proveedor no coincide.'); END IF;
 IF P_ESTADO NOT IN ('APROBADO','RECHAZADO','REEMBOLSADO') OR P_ESTADO IS NULL THEN RAISE_APPLICATION_ERROR(-20700,'Estado de pago no permitido.'); END IF;
 NUEVO:=P_ESTADO;
 IF P_ESTADO='APROBADO' AND PED_EST='CANCELADO' THEN NUEVO:='REEMBOLSO_PENDIENTE'; END IF;
 -- Un fallo tardío no deshace un pago confirmado o un reembolso.
 IF (ACTUAL IN ('APROBADO','REEMBOLSO_PENDIENTE','REEMBOLSADO') AND P_ESTADO='RECHAZADO') OR ACTUAL='REEMBOLSADO' OR ACTUAL=NUEVO THEN
 NUEVO:=ACTUAL;
 END IF;
 IF NUEVO<>ACTUAL THEN
 SELECT ID_ESTADO_PAGO INTO EST_ID FROM ESTADO_PAGO WHERE CODIGO=NUEVO;
 UPDATE PAGO SET ID_ESTADO_PAGO=EST_ID,REFERENCIA_PROV=COALESCE(REFERENCIA_PROV,P_REFERENCIA),FECHA_CONFIRMACION=CASE WHEN P_ESTADO='APROBADO' THEN SYSTIMESTAMP ELSE FECHA_CONFIRMACION END,OBSERVACIONES='Recurrente: '||SUBSTR(P_TIPO,1,80) WHERE ID_PAGO=ID_P;
 INSERT INTO PEDIDO_ESTADO_HISTORIAL(ID_PEDIDO,ID_ESTADO_PEDIDO,COMENTARIO) SELECT PED,ID_ESTADO_PEDIDO,CASE NUEVO WHEN 'APROBADO' THEN 'Pago con tarjeta confirmado.' WHEN 'RECHAZADO' THEN 'Pago rechazado. Puedes reintentar.' WHEN 'REEMBOLSO_PENDIENTE' THEN 'Pago recibido después de cancelar. Reembolso pendiente.' ELSE 'Reembolso confirmado.' END FROM PEDIDO WHERE ID_PEDIDO=PED;
 END IF;
 INSERT INTO PAGO_EVENTO_PROVEEDOR(PROVEEDOR,ENTORNO,ID_EVENTO_PROVEEDOR,ID_CHECKOUT_PROVEEDOR,ID_PAGO,TIPO_EVENTO,FECHA_PROCESAMIENTO,ESTADO) VALUES('RECURRENTE',P_ENTORNO,P_EVENTO,P_CHECKOUT,ID_P,P_TIPO,SYSTIMESTAMP,'PROCESADO');
 END;
END PKG_COMPRA;
/
