DECLARE N NUMBER;
BEGIN
 -- Crear primero el reemplazo; no quitar la protección si hay duplicados reales.
 SELECT COUNT(*) INTO N FROM USER_INDEXES WHERE INDEX_NAME='UX_PAGO_REFERENCIA_CONFIRMADA';
 IF N=0 THEN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_PAGO_REFERENCIA_CONFIRMADA ON PAGO(CASE WHEN REFERENCIA_PROV IS NOT NULL THEN PROVEEDOR_PAGO END,CASE WHEN REFERENCIA_PROV IS NOT NULL THEN ENTORNO END,REFERENCIA_PROV)';
 END IF;
 SELECT COUNT(*) INTO N FROM USER_CONSTRAINTS WHERE TABLE_NAME='PAGO' AND CONSTRAINT_NAME='UK_PAGO_PROVEEDOR';
 IF N=1 THEN EXECUTE IMMEDIATE 'ALTER TABLE PAGO DROP CONSTRAINT UK_PAGO_PROVEEDOR'; END IF;
 SELECT COUNT(*) INTO N FROM USER_INDEXES WHERE TABLE_NAME='PAGO' AND INDEX_NAME='UK_PAGO_PROVEEDOR';
 IF N=1 THEN EXECUTE IMMEDIATE 'DROP INDEX UK_PAGO_PROVEEDOR'; END IF;
END;
/
