DECLARE
    V_EXISTE NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_EXISTE FROM USER_TABLES WHERE TABLE_NAME = 'RECUPERACION_PASSWORD';
    IF V_EXISTE = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE RECUPERACION_PASSWORD (
            ID_USUARIO NUMBER(19) NOT NULL,
            SOLICITUD VARCHAR2(64),
            ESTADO CLOB NOT NULL,
            CONSTRAINT PK_RECUP_PASSWORD PRIMARY KEY (ID_USUARIO),
            CONSTRAINT UK_RECUP_PASSWORD_SOL UNIQUE (SOLICITUD),
            CONSTRAINT FK_RECUP_PASSWORD_USR FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
            CONSTRAINT CK_RECUP_PASSWORD_JSON CHECK (ESTADO IS JSON)
        )';
    END IF;
END;
/
