DECLARE n NUMBER;
BEGIN
 SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME='COMPRA_CONSTANCIA';
 IF n=0 THEN EXECUTE IMMEDIATE 'CREATE TABLE COMPRA_CONSTANCIA (
 ID_PEDIDO NUMBER NOT NULL REFERENCES PEDIDO(ID_PEDIDO), CANAL VARCHAR2(10) NOT NULL,
 DESTINO VARCHAR2(320) NOT NULL, ESTADO VARCHAR2(12) DEFAULT ''PENDIENTE'' NOT NULL,
 PDF BLOB, TOKEN VARCHAR2(64), EXPIRA TIMESTAMP WITH TIME ZONE,
 CREADO TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 CONSTRAINT PK_COMPRA_CONSTANCIA PRIMARY KEY(ID_PEDIDO,CANAL),
 CONSTRAINT UK_CONSTANCIA_TOKEN UNIQUE(TOKEN),
 CONSTRAINT CK_CONSTANCIA_CANAL CHECK(CANAL IN (''EMAIL'',''WHATSAPP'')))'; END IF;
END;
/
