DECLARE n NUMBER;
BEGIN
 SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME='CREDENCIAL';
 IF n=0 THEN EXECUTE IMMEDIATE 'CREATE TABLE CREDENCIAL (
 ID_USUARIO NUMBER PRIMARY KEY REFERENCES USUARIO(ID_USUARIO), VERSION VARCHAR2(32) NOT NULL,
 FOTO BLOB NOT NULL, PDF_CIFRADO BLOB NOT NULL, EMITIDA TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL)'; END IF;
 SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME='CREDENCIAL_ENVIO';
 IF n=0 THEN EXECUTE IMMEDIATE 'CREATE TABLE CREDENCIAL_ENVIO (
 ID_USUARIO NUMBER NOT NULL REFERENCES USUARIO(ID_USUARIO), CANAL VARCHAR2(10) NOT NULL,
 VERSION VARCHAR2(32) NOT NULL, DESTINO VARCHAR2(320) NOT NULL,
 ESTADO VARCHAR2(12) DEFAULT ''PENDIENTE'' NOT NULL, TOKEN VARCHAR2(64),
 EXPIRA TIMESTAMP WITH TIME ZONE, SOLICITADO TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 PRIMARY KEY(ID_USUARIO,CANAL), UNIQUE(TOKEN))'; END IF;
END;
/
