DECLARE n NUMBER;
BEGIN
 SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS WHERE TABLE_NAME='CREDENCIAL' AND COLUMN_NAME='TEMA';
 IF n=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE CREDENCIAL ADD TEMA VARCHAR2(10) DEFAULT ''AZUL'' NOT NULL'; END IF;
END;
/
