-- 1. Crear el usuario
CREATE USER TIENDA_APP IDENTIFIED BY "tienda_Oracle_2026" 
    DEFAULT TABLESPACE USERS 
    TEMPORARY TABLESPACE TEMP 
    QUOTA UNLIMITED ON USERS;

-- 2. Otorgar privilegios necesarios
GRANT CONNECT, RESOURCE, CREATE SESSION TO TIENDA_APP;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO TIENDA_APP;

-- 3. (Opcional pero recomendado) Otorgar permisos para crear índices y comentarios
GRANT UNLIMITED TABLESPACE TO TIENDA_APP;