/*
    -- VISTAS DE CONSULTA PARA PACKAGES FUTUROS
*/

CREATE OR REPLACE VIEW VW_PEDIDO_RESUMEN AS
SELECT
    P.ID_PEDIDO,
    P.NUMERO_PEDIDO,
    P.FECHA_PEDIDO,
    P.ID_USUARIO,
    U.NICKNAME AS COMPRADOR,
    U.CORREO,
    P.ID_SITIO,
    S.NOMBRE AS SITIO,
    EP.CODIGO AS CODIGO_ESTADO,
    EP.NOMBRE AS ESTADO_PEDIDO,
    AE.NOMBRE AS AREA_ENTREGA,
    P.SUBTOTAL,
    P.CARGO_ENTREGA,
    P.TOTAL,
    P.COD_MONEDA
FROM PEDIDO P
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SITIO S ON S.ID_SITIO = P.ID_SITIO
INNER JOIN ESTADO_PEDIDO EP ON EP.ID_ESTADO_PEDIDO = P.ID_ESTADO_PEDIDO
INNER JOIN AREA_ENTREGA AE ON AE.ID_AREA_ENTREGA = P.ID_AREA_ENTREGA;

CREATE OR REPLACE VIEW VW_TRACKING_PEDIDO AS
SELECT
    P.ID_PEDIDO,
    P.NUMERO_PEDIDO,
    H.ID_HISTORIAL,
    EP.CODIGO AS CODIGO_ESTADO,
    EP.NOMBRE AS ESTADO,
    EP.ORDEN_VISUAL,
    H.FECHA_ESTADO,
    H.COMENTARIO,
    H.ID_USUARIO_ACTOR,
    U.NICKNAME AS USUARIO_ACTOR
FROM PEDIDO P
INNER JOIN PEDIDO_ESTADO_HISTORIAL H ON H.ID_PEDIDO = P.ID_PEDIDO
INNER JOIN ESTADO_PEDIDO EP ON EP.ID_ESTADO_PEDIDO = H.ID_ESTADO_PEDIDO
LEFT JOIN USUARIO U ON U.ID_USUARIO = H.ID_USUARIO_ACTOR;

CREATE OR REPLACE VIEW VW_VENTAS_DASHBOARD AS
SELECT
    P.ID_PEDIDO,
    P.NUMERO_PEDIDO,
    P.FECHA_PEDIDO,
    P.ID_SITIO,
    S.NOMBRE AS SITIO,
    EP.CODIGO AS CODIGO_ESTADO,
    EP.NOMBRE AS ESTADO_PEDIDO,
    PD.ID_PRODUCTO,
    PD.SKU_PRODUCTO,
    PD.NOMBRE_PRODUCTO,
    CP.NOMBRE AS CATEGORIA,
    PD.CANTIDAD,
    PD.PRECIO_UNITARIO,
    PD.PRECIO_PERSONALIZA,
    PD.SUBTOTAL AS TOTAL_LINEA,
    P.TOTAL AS TOTAL_PEDIDO,
    P.COD_MONEDA
FROM PEDIDO P
INNER JOIN PEDIDO_DETALLE PD ON PD.ID_PEDIDO = P.ID_PEDIDO
INNER JOIN PRODUCTO PR ON PR.ID_PRODUCTO = PD.ID_PRODUCTO
INNER JOIN CATEGORIA_PRODUCTO CP ON CP.ID_CATEGORIA = PR.ID_CATEGORIA
INNER JOIN ESTADO_PEDIDO EP ON EP.ID_ESTADO_PEDIDO = P.ID_ESTADO_PEDIDO
INNER JOIN SITIO S ON S.ID_SITIO = P.ID_SITIO;