/*
    -- DATOS INICIALES DE CATALOGOS
*/

INSERT INTO SITIO (CODIGO, NOMBRE, ACTIVO)
VALUES ('TIENDA01', 'Tienda Proyecto', 'S');

INSERT INTO ROL (CODIGO, NOMBRE, DESCRIPCION)
VALUES ('ADMIN', 'Administrador', 'Gestion de usuarios, roles y parametrizaciones.');
INSERT INTO ROL (CODIGO, NOMBRE, DESCRIPCION)
VALUES ('SUPERVISOR', 'Supervisor', 'Consulta dashboard, ventas y entregas.');
INSERT INTO ROL (CODIGO, NOMBRE, DESCRIPCION)
VALUES ('REPARTIDOR', 'Repartidor', 'Consulta y registro de entregas asignadas.');
INSERT INTO ROL (CODIGO, NOMBRE, DESCRIPCION)
VALUES ('COMPRADOR', 'Comprador', 'Compras, tracking, historico y perfil.');

INSERT INTO PERMISO (CODIGO, NOMBRE, MODULO) VALUES
('GESTIONAR_USUARIOS', 'Gestionar usuarios', 'SEGURIDAD');
INSERT INTO PERMISO (CODIGO, NOMBRE, MODULO) VALUES
('GESTIONAR_ROLES', 'Gestionar roles y permisos', 'SEGURIDAD');
INSERT INTO PERMISO (CODIGO, NOMBRE, MODULO) VALUES
('GESTIONAR_CATALOGOS', 'Gestionar catalogos', 'ADMINISTRACION');
INSERT INTO PERMISO (CODIGO, NOMBRE, MODULO) VALUES
('VER_DASHBOARD', 'Consultar dashboard de ventas', 'DASHBOARD');
INSERT INTO PERMISO (CODIGO, NOMBRE, MODULO) VALUES
('GESTIONAR_ENTREGAS', 'Gestionar entregas', 'ENTREGAS');
INSERT INTO PERMISO (CODIGO, NOMBRE, MODULO) VALUES
('CREAR_PEDIDO', 'Crear pedidos', 'COMPRAS');
INSERT INTO PERMISO (CODIGO, NOMBRE, MODULO) VALUES
('VER_TRACKING', 'Consultar tracking', 'COMPRAS');
INSERT INTO PERMISO (CODIGO, NOMBRE, MODULO) VALUES
('VER_HISTORICO', 'Consultar historico de compras', 'COMPRAS');
INSERT INTO PERMISO (CODIGO, NOMBRE, MODULO) VALUES
('GESTIONAR_PERFIL', 'Gestionar perfil propio', 'PERFIL');

-- ADMIN recibe todos los permisos.
INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO)
SELECT R.ID_ROL, P.ID_PERMISO
FROM ROL R CROSS JOIN PERMISO P
WHERE R.CODIGO = 'ADMIN';

-- SUPERVISOR.
INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO)
SELECT R.ID_ROL, P.ID_PERMISO
FROM ROL R CROSS JOIN PERMISO P
WHERE R.CODIGO = 'SUPERVISOR'
  AND P.CODIGO IN ('VER_DASHBOARD', 'GESTIONAR_ENTREGAS', 'GESTIONAR_PERFIL');

-- REPARTIDOR.
INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO)
SELECT R.ID_ROL, P.ID_PERMISO
FROM ROL R CROSS JOIN PERMISO P
WHERE R.CODIGO = 'REPARTIDOR'
  AND P.CODIGO IN ('GESTIONAR_ENTREGAS', 'GESTIONAR_PERFIL');

-- COMPRADOR.
INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO)
SELECT R.ID_ROL, P.ID_PERMISO
FROM ROL R CROSS JOIN PERMISO P
WHERE R.CODIGO = 'COMPRADOR'
  AND P.CODIGO IN ('CREAR_PEDIDO', 'VER_TRACKING', 'VER_HISTORICO', 'GESTIONAR_PERFIL');

INSERT INTO CATEGORIA_PRODUCTO (CODIGO, NOMBRE)
VALUES ('ANILLOS', 'Anillos');
INSERT INTO CATEGORIA_PRODUCTO (CODIGO, NOMBRE)
VALUES ('LLAVEROS', 'Llaveros');
INSERT INTO CATEGORIA_PRODUCTO (CODIGO, NOMBRE)
VALUES ('TAZAS', 'Tazas');

INSERT INTO METODO_PAGO (CODIGO, NOMBRE, REQUIERE_PROVEEDOR)
VALUES ('EFECTIVO', 'Efectivo contra entrega', 'N');
INSERT INTO METODO_PAGO (CODIGO, NOMBRE, REQUIERE_PROVEEDOR)
VALUES ('TARJETA', 'Tarjeta de credito o debito', 'S');

INSERT INTO ESTADO_PEDIDO
    (CODIGO, NOMBRE, DESCRIPCION, ORDEN_VISUAL, ES_FINAL)
VALUES
    ('GENERADO', 'Pedido generado', 'Orden creada al finalizar el checkout.', 1, 'N');
INSERT INTO ESTADO_PEDIDO
    (CODIGO, NOMBRE, DESCRIPCION, ORDEN_VISUAL, ES_FINAL)
VALUES
    ('PAGO_PENDIENTE', 'Pago pendiente', 'Pendiente de confirmar pago o cobrar efectivo.', 2, 'N');
INSERT INTO ESTADO_PEDIDO
    (CODIGO, NOMBRE, DESCRIPCION, ORDEN_VISUAL, ES_FINAL)
VALUES
    ('PAGO_CONFIRMADO', 'Pago confirmado', 'Pago confirmado para iniciar elaboracion.', 3, 'N');
INSERT INTO ESTADO_PEDIDO
    (CODIGO, NOMBRE, DESCRIPCION, ORDEN_VISUAL, ES_FINAL)
VALUES
    ('EN_ELABORACION', 'En elaboracion', 'Producto personalizado en proceso.', 4, 'N');
INSERT INTO ESTADO_PEDIDO
    (CODIGO, NOMBRE, DESCRIPCION, ORDEN_VISUAL, ES_FINAL)
VALUES
    ('LISTO_ENTREGA', 'Listo para entrega', 'Producto terminado y disponible para entregar.', 5, 'N');
INSERT INTO ESTADO_PEDIDO
    (CODIGO, NOMBRE, DESCRIPCION, ORDEN_VISUAL, ES_FINAL)
VALUES
    ('ENTREGADO', 'Entregado', 'Producto entregado al comprador.', 6, 'S');
INSERT INTO ESTADO_PEDIDO
    (CODIGO, NOMBRE, DESCRIPCION, ORDEN_VISUAL, ES_FINAL)
VALUES
    ('COMPRADOR_NO_ENCONTRADO', 'Comprador no encontrado', 'Intento de entrega sin localizar al comprador.', 7, 'N');
INSERT INTO ESTADO_PEDIDO
    (CODIGO, NOMBRE, DESCRIPCION, ORDEN_VISUAL, ES_FINAL)
VALUES
    ('CANCELADO', 'Cancelado', 'Pedido cancelado.', 8, 'S');

INSERT INTO ESTADO_PAGO (CODIGO, NOMBRE, ES_FINAL)
VALUES ('PENDIENTE', 'Pendiente', 'N');
INSERT INTO ESTADO_PAGO (CODIGO, NOMBRE, ES_FINAL)
VALUES ('APROBADO', 'Aprobado', 'S');
INSERT INTO ESTADO_PAGO (CODIGO, NOMBRE, ES_FINAL)
VALUES ('RECHAZADO', 'Rechazado', 'S');
INSERT INTO ESTADO_PAGO (CODIGO, NOMBRE, ES_FINAL)
VALUES ('PAGADO_EFECTIVO', 'Pagado en efectivo', 'S');
INSERT INTO ESTADO_PAGO (CODIGO, NOMBRE, ES_FINAL)
VALUES ('ANULADO', 'Anulado', 'S');

INSERT INTO ESTADO_ENTREGA (CODIGO, NOMBRE, ES_FINAL)
VALUES ('PENDIENTE', 'Pendiente', 'N');
INSERT INTO ESTADO_ENTREGA (CODIGO, NOMBRE, ES_FINAL)
VALUES ('ASIGNADA', 'Asignada', 'N');
INSERT INTO ESTADO_ENTREGA (CODIGO, NOMBRE, ES_FINAL)
VALUES ('ENTREGADA', 'Entregada', 'S');
INSERT INTO ESTADO_ENTREGA (CODIGO, NOMBRE, ES_FINAL)
VALUES ('NO_ENCONTRADO', 'Comprador no encontrado', 'N');
INSERT INTO ESTADO_ENTREGA (CODIGO, NOMBRE, ES_FINAL)
VALUES ('CANCELADA', 'Cancelada', 'S');

COMMIT;


/*
    -- VALIDACION FINAL
*/

DECLARE
    V_TABLAS     NUMBER;
    V_VISTAS     NUMBER;
    V_TRIGGERS   NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_TABLAS
    FROM USER_TABLES
    WHERE TABLE_NAME IN (
        'SITIO', 'ARCHIVO', 'ROL', 'PERMISO', 'USUARIO', 'USUARIO_ROL',
        'ROL_PERMISO', 'TOKEN_RECUPERACION', 'BITACORA_ACCESO',
        'CATEGORIA_PRODUCTO', 'PRODUCTO', 'METODO_PAGO', 'ESTADO_PEDIDO',
        'ESTADO_PAGO', 'ESTADO_ENTREGA', 'AREA_ENTREGA', 'CARRITO',
        'PERSONALIZACION', 'CARRITO_DETALLE', 'PEDIDO', 'PEDIDO_DETALLE',
        'PEDIDO_ESTADO_HISTORIAL', 'PAGO', 'ENTREGA'
    );

    SELECT COUNT(*) INTO V_VISTAS
    FROM USER_VIEWS
    WHERE VIEW_NAME IN (
        'VW_PEDIDO_RESUMEN', 'VW_TRACKING_PEDIDO', 'VW_VENTAS_DASHBOARD'
    );

    SELECT COUNT(*) INTO V_TRIGGERS
    FROM USER_TRIGGERS
    WHERE TRIGGER_NAME IN (
        'TRG_SITIO_BU_FECHA', 'TRG_USUARIO_BU_FECHA',
        'TRG_PRODUCTO_BU_FECHA', 'TRG_CARRITO_BU_FECHA',
        'TRG_PEDIDO_BU_FECHA'
    );

    DBMS_OUTPUT.PUT_LINE('Tablas esperadas: 24 / creadas: ' || V_TABLAS);
    DBMS_OUTPUT.PUT_LINE('Vistas esperadas: 3 / creadas: ' || V_VISTAS);
    DBMS_OUTPUT.PUT_LINE('Triggers esperados: 5 / creados: ' || V_TRIGGERS);

    IF V_TABLAS <> 24 OR V_VISTAS <> 3 OR V_TRIGGERS <> 5 THEN
        RAISE_APPLICATION_ERROR(-20001, 'La validacion de objetos no coincide.');
    END IF;

    DBMS_OUTPUT.PUT_LINE('DDL BASE FINAL ejecutado correctamente.');
END;
/


