import { useEffect, useRef, useState } from 'react';
import { obtenerToken } from '../api/famkon';
import { comprasRequest, descargarCompra } from '../api/compras';
import CameraCapture, { type CameraCaptureHandle } from './CameraCapture';
import EditorFotoCredencial from './EditorFotoCredencial';
export default function MiCredencial(){
 const [preview,setPreview]=useState('');
 const [solicitudRostro,setSolicitudRostro]=useState('');
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 async function ver(){try{const r=await fetch('/api/famkon/credencial/pdf',{headers:{Authorization:`Bearer ${obtenerToken()}`}});if(!r.ok)throw new Error('No se pudo abrir la credencial.');setPreview(URL.createObjectURL(await r.blob()));}catch(e){setMensaje((e as Error).message);}}
 const [existe,setExiste]=useState(false);const [foto,setFoto]=useState('');const [editada,setEditada]=useState('');const [mensaje,setMensaje]=useState('');const [busy,setBusy]=useState(false);const [editor,setEditor]=useState(false);const [reemplazar,setReemplazar]=useState(false);const [envios,setEnvios]=useState<{canal:string;estado:string}[]>([]);const camera=useRef<CameraCaptureHandle>(null);
 async function cargar(){const d=await comprasRequest<{existe:boolean;envios:{canal:string;estado:string}[]}>('/credencial', {signal: AbortSignal.timeout(15000)});setExiste(d.existe);setEnvios(d.envios);}
 useEffect(()=>{void cargar().catch(()=>setMensaje('No se pudo consultar tu credencial.'));},[]);
 async function accion(path:string,body?:object){setBusy(true);setMensaje('');try{const r=await comprasRequest<{mensaje:string}>(path,{method:'POST',signal:AbortSignal.timeout(45000),...(body?{body:JSON.stringify(body)}:{})});setMensaje(r.mensaje);setExiste(true);void cargar().catch(()=>setMensaje(r.mensaje+' No se pudo actualizar el estado del envío.'));setEditor(false);setReemplazar(false);setPreview('');camera.current?.apagar();window.dispatchEvent(new Event('credencial-actualizada'));}catch(e){const err=e as Error;setMensaje(err.name==='TimeoutError'||err.name==='AbortError'?'El servidor tardó demasiado. Consulta Mi credencial antes de volver a crearla: la operación podría haberse completado.':err.message);}finally{setBusy(false);}}
 return <section className="rounded-2xl border bg-white p-6 space-y-4"><h2 className="text-lg font-bold">Mi credencial</h2><p className="text-sm">Tu fotografía personalizada y QR de acceso. Este documento permite entrar a tu cuenta: no lo compartas.</p><div className="flex flex-wrap gap-3">{existe&&<><button disabled={busy} onClick={ver} className="rounded-lg border p-3">Ver credencial</button><button disabled={busy} onClick={()=>descargarCompra('/credencial/pdf','credencial-famkon.pdf').catch(e=>setMensaje(e.message))} className="rounded-lg bg-amber-500 p-3">Descargar PDF</button><button disabled={busy} onClick={()=>accion('/credencial/reenviar')} className="rounded-lg border p-3">Reenviar</button><button disabled={busy} onClick={()=>setReemplazar(true)} className="rounded-lg border p-3">Reemplazar QR</button></>}<button disabled={busy} onClick={()=>setEditor(v=>!v)} className="rounded-lg border p-3">{editor?'Cerrar editor':existe?'Cambiar diseño':'Crear credencial'}</button></div>{reemplazar&&<div className="rounded-lg bg-amber-50 p-4"><p>El QR de la credencial anterior dejará de permitir el acceso.</p><button disabled={busy} onClick={()=>accion('/credencial/reemplazar')} className="mt-2 font-bold">Confirmar reemplazo</button><button onClick={()=>setReemplazar(false)} className="ml-4">Cancelar</button></div>}
 {preview&&<div><button onClick={()=>setPreview('')} className="mb-2 text-sm underline">Cerrar vista previa</button><iframe title="Tu credencial PDF" src={preview} className="h-[600px] w-full rounded-lg border"/></div>}
 {editor&&<div className="space-y-3"><CameraCapture ref={camera}/><button onClick={()=>{const f=camera.current?.capturar();if(f){setEditada('');setSolicitudRostro('');setFoto(f);}else setMensaje('Activa la cámara primero.');}} className="rounded-lg border p-3">Tomar foto</button><label className="block text-sm">O selecciona una foto<input type="file" accept="image/jpeg,image/png" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>2_000_000){setMensaje('Usa una imagen de hasta 2 MB.');return;}const r=new FileReader();r.onload=()=>{setEditada('');setSolicitudRostro('');setFoto(String(r.result));};r.readAsDataURL(file);}}/></label>{foto&&<EditorFotoCredencial key={foto} original={foto} onChange={setEditada} onPreparada={setSolicitudRostro}/>}<p className="text-xs">Guardar un diseño nuevo reemplaza también el QR anterior.</p><button disabled={busy||!editada||!solicitudRostro} onClick={()=>accion('/credencial',{fotoOriginal:foto,fotoEditada:editada,solicitudRostro})} className="rounded-lg bg-amber-500 p-3 disabled:opacity-50">{busy?'Creando…':'Guardar y enviar credencial'}</button></div>}
 {envios.map(e=><p key={e.canal} className="text-xs">{e.canal}: {e.estado}</p>)}{mensaje&&<p role="status" className="text-sm">{mensaje}</p>}</section>;
}
