import { useEffect, useRef, useState } from 'react';
import { obtenerToken } from '../api/famkon';
import { comprasRequest, descargarCompra } from '../api/compras';
import CameraCapture, { type CameraCaptureHandle } from './CameraCapture';
import EditorFotoCredencial from './EditorFotoCredencial';
import VistaPreviaCarnet from './VistaPreviaCarnet';
import { useAuth } from '../context/AuthContext';
import { Camera, Download, Eye, IdCard, RefreshCw, Send, ShieldCheck, Upload } from 'lucide-react';
export default function MiCredencial(){
 const {usuario}=useAuth();
 const [preview,setPreview]=useState('');
 const [solicitudRostro,setSolicitudRostro]=useState('');
 const [tema,setTema]=useState('AZUL');
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 async function ver(){try{const r=await fetch('/api/famkon/credencial/pdf',{headers:{Authorization:`Bearer ${obtenerToken()}`}});if(!r.ok)throw new Error('No se pudo abrir la credencial.');setPreview(URL.createObjectURL(await r.blob()));}catch(e){setMensaje((e as Error).message);}}
 const [existe,setExiste]=useState(false);const [foto,setFoto]=useState('');const [editada,setEditada]=useState('');const [mensaje,setMensaje]=useState('');const [busy,setBusy]=useState(false);const [editor,setEditor]=useState(false);const [reemplazar,setReemplazar]=useState(false);const [envios,setEnvios]=useState<{canal:string;estado:string}[]>([]);const camera=useRef<CameraCaptureHandle>(null);
 async function cargar(){const d=await comprasRequest<{existe:boolean;tema?:string;envios:{canal:string;estado:string}[]}>('/credencial', {signal: AbortSignal.timeout(15000)});setExiste(d.existe);setTema(d.tema||'AZUL');setEnvios(d.envios);}
 useEffect(()=>{void cargar().catch(()=>setMensaje('No se pudo consultar tu credencial.'));},[]);
 async function accion(path:string,body?:object){setBusy(true);setMensaje('');try{const r=await comprasRequest<{mensaje:string}>(path,{method:'POST',signal:AbortSignal.timeout(45000),...(body?{body:JSON.stringify(body)}:{})});setMensaje(r.mensaje);setExiste(true);void cargar().catch(()=>setMensaje(r.mensaje+' No se pudo actualizar el estado del envío.'));setEditor(false);setReemplazar(false);setPreview('');camera.current?.apagar();window.dispatchEvent(new Event('credencial-actualizada'));}catch(e){const err=e as Error;setMensaje(err.name==='TimeoutError'||err.name==='AbortError'?'El servidor tardó demasiado. Consulta Mi credencial antes de volver a crearla: la operación podría haberse completado.':err.message);}finally{setBusy(false);}}
 const boton='inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700 transition hover:border-orange-300 hover:bg-orange-50 disabled:opacity-50';
 return <section className="space-y-5 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6 lg:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-orange-100 text-orange-700"><IdCard size={22}/></span><div><h2 className="text-lg font-bold text-slate-950">Mi credencial</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-600">Personaliza tu fotografía y administra el QR de acceso. Es un documento personal: no lo compartas.</p></div></div><span className={`inline-flex w-fit items-center gap-2 rounded-full px-3 py-1.5 text-xs font-bold ${existe?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}><ShieldCheck size={14}/>{existe?'Credencial activa':'Sin crear'}</span></div>
 <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:flex lg:flex-wrap">{existe&&<><button disabled={busy} onClick={ver} className={boton}><Eye size={17}/>Ver credencial</button><button disabled={busy} onClick={()=>descargarCompra('/credencial/pdf','credencial-famkon.pdf').catch(e=>setMensaje(e.message))} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-orange-500 px-4 py-3 text-sm font-bold text-white hover:bg-orange-600 disabled:opacity-50"><Download size={17}/>Descargar PDF</button><button disabled={busy} onClick={()=>accion('/credencial/reenviar')} className={boton}><Send size={17}/>Reenviar</button><button disabled={busy} onClick={()=>setReemplazar(true)} className={boton}><RefreshCw size={17}/>Reemplazar QR</button></>}<button disabled={busy} onClick={()=>setEditor(v=>!v)} className={boton}><Camera size={17}/>{editor?'Cerrar editor':existe?'Cambiar foto y filtros':'Crear credencial'}</button></div>
 {reemplazar&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><p className="font-semibold">El QR de la credencial anterior dejará de permitir el acceso.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><button disabled={busy} onClick={()=>accion('/credencial/reemplazar')} className="min-h-11 rounded-xl bg-amber-500 px-4 font-bold">Confirmar reemplazo</button><button onClick={()=>setReemplazar(false)} className="min-h-11 rounded-xl px-4 font-semibold">Cancelar</button></div></div>}
 {preview&&<div className="rounded-2xl border border-slate-200 p-3"><button onClick={()=>setPreview('')} className="mb-3 min-h-10 text-sm font-semibold text-orange-700">Cerrar vista previa</button><iframe title="Tu credencial PDF" src={preview} className="h-[70vh] min-h-[430px] w-full rounded-xl border"/></div>}
 {editor&&<div className="space-y-5 border-t border-slate-100 pt-5"><div><h3 className="font-bold text-slate-950">1. Elige una fotografía</h3><p className="mt-1 text-sm text-slate-500">Mira de frente, utiliza buena iluminación y deja visible el rostro completo.</p></div><CameraCapture ref={camera}/><div className="grid gap-2 sm:grid-cols-2"><button onClick={()=>{const f=camera.current?.capturar();if(f){setEditada('');setSolicitudRostro('');setFoto(f);}else setMensaje('Activa la cámara primero.');}} className={boton}><Camera size={17}/>Tomar foto</button><label className={`${boton} cursor-pointer`}><Upload size={17}/>Seleccionar archivo<input className="sr-only" type="file" accept="image/jpeg,image/png" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>2_000_000){setMensaje('Usa una imagen de hasta 2 MB.');return;}const r=new FileReader();r.onload=()=>{setEditada('');setSolicitudRostro('');setFoto(String(r.result));};r.readAsDataURL(file);}}/></label></div>{foto&&<><div><h3 className="mb-3 font-bold text-slate-950">2. Personaliza el diseño</h3><EditorFotoCredencial key={foto} original={foto} onChange={setEditada} onPreparada={setSolicitudRostro}/></div>{editada&&<VistaPreviaCarnet foto={editada} nickname={usuario?.nickname||'Tu nickname'} tema={tema} onTema={setTema}/>}<div className="rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-600">Al guardar un diseño nuevo se genera un QR diferente y el anterior deja de funcionar.</div><button disabled={busy||!editada||!solicitudRostro} onClick={()=>accion('/credencial',{fotoOriginal:foto,fotoEditada:editada,solicitudRostro,tema})} className="min-h-12 w-full rounded-xl bg-orange-500 px-5 font-bold text-white hover:bg-orange-600 disabled:opacity-50 sm:w-auto">{busy?'Creando…':'Guardar y enviar credencial'}</button></>}</div>}
 {envios.length>0&&<div className="flex flex-wrap gap-2 border-t border-slate-100 pt-4">{envios.map(e=><span key={e.canal} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-medium text-slate-600">{e.canal==='EMAIL'?'Correo':'WhatsApp'}: {e.estado}</span>)}</div>}{mensaje&&<p role="status" className="rounded-xl bg-slate-50 p-3 text-sm text-slate-700">{mensaje}</p>}</section>;
}
