DECLARE
 S NUMBER; U NUMBER; A NUMBER; R NUMBER; EXTRA NUMBER; CAT NUMBER; PROD NUMBER; C NUMBER; P NUMBER; P2 NUMBER; P3 NUMBER; P4 NUMBER; ARCH NUMBER; N NUMBER; V NUMBER;
 SUF VARCHAR2(20):=SUBSTR(RAWTOHEX(SYS_GUID()),1,16);
 PROCEDURE OK(B BOOLEAN,M VARCHAR2) IS BEGIN IF B IS NULL OR NOT B THEN RAISE_APPLICATION_ERROR(-20999,'TEST: '||M); END IF; END;
 PROCEDURE USER_NEW(ROL_C VARCHAR2,OUT_ID OUT NUMBER) IS
 BEGIN
 INSERT INTO USUARIO(ID_SITIO,CORREO,NICKNAME,TELEFONO,PASSWORD_HASH,TOKEN_QR_HASH,NOTIFICA_EMAIL,NOTIFICA_WHATSAPP)
 VALUES(S,'qa-'||ROL_C||'-'||SUF||'@example.invalid','qa-'||ROL_C||'-'||SUF,'55555555','not-a-password',RAWTOHEX(SYS_GUID()),'S','N') RETURNING ID_USUARIO INTO OUT_ID;
 INSERT INTO USUARIO_ROL(ID_USUARIO,ID_ROL) SELECT OUT_ID,ID_ROL FROM ROL WHERE CODIGO=ROL_C;
 END;
 PROCEDURE CART_NEW IS D NUMBER; BEGIN
 INSERT INTO CARRITO(ID_USUARIO,ID_SITIO) VALUES(U,S) RETURNING ID_CARRITO INTO C;
 PKG_CARRITO.SP_AGREGAR_PRODUCTO(C,PROD,NULL,2,0,D);
 END;
 PROCEDURE FAIL(SQL_TEXT VARCHAR2,CODE NUMBER) IS GOT NUMBER:=0; BEGIN
 SAVEPOINT INVALID_ACTION;
 BEGIN EXECUTE IMMEDIATE SQL_TEXT; EXCEPTION WHEN OTHERS THEN GOT:=SQLCODE; END;
 ROLLBACK TO INVALID_ACTION; OK(GOT=CODE,'rechazo esperado '||CODE||', recibido '||GOT);
 END;
BEGIN
 SELECT MIN(ID_SITIO) INTO S FROM SITIO WHERE ACTIVO='S';
 USER_NEW('COMPRADOR',U); USER_NEW('ADMIN',A); USER_NEW('REPARTIDOR',R);
 INSERT INTO USUARIO(ID_SITIO,CORREO,NICKNAME,TELEFONO,PASSWORD_HASH,TOKEN_QR_HASH,NOTIFICA_EMAIL,NOTIFICA_WHATSAPP)
 VALUES(S,'qa-extra-'||SUF||'@example.invalid','qa-extra-'||SUF,'55555555','not-a-password',RAWTOHEX(SYS_GUID()),'S','N') RETURNING ID_USUARIO INTO EXTRA;
 INSERT INTO CATEGORIA_PRODUCTO(CODIGO,NOMBRE) VALUES('QA-'||SUF,'Prueba transaccional') RETURNING ID_CATEGORIA INTO CAT;
 INSERT INTO PRODUCTO(ID_SITIO,ID_CATEGORIA,SKU,NOMBRE,PRECIO_BASE) VALUES(S,CAT,'QA-'||SUF,'Producto de prueba',50) RETURNING ID_PRODUCTO INTO PROD;
 CART_NEW;
 FAIL('DECLARE P NUMBER; BEGIN PKG_COMPRA.CREAR('||EXTRA||','||C||',1,''55555555'',NULL,NULL,NULL,NULL,NULL,''EFECTIVO'',''TEST'',P); END;',-20703);
 PKG_COMPRA.CREAR(U,C,1,'55555555',NULL,NULL,NULL,NULL,NULL,'EFECTIVO','TEST',P);
 SELECT CARGO_ENTREGA,TOTAL INTO N,V FROM PEDIDO WHERE ID_PEDIDO=P; OK(N=0 AND V=100,'total tienda');
 PKG_COMPRA.CREAR(U,C,1,'55555555',NULL,NULL,NULL,NULL,NULL,'EFECTIVO','TEST',P2); OK(P=P2,'doble checkout idempotente');
 OK(PKG_COMPRA.PUEDE_VER(P,EXTRA,'cliente')=0,'aislamiento comprador');
 FAIL('BEGIN PKG_COMPRA.AVANZAR('||P||','||U||',''EN_ELABORACION'',NULL); END;',-20703);
 FAIL('BEGIN PKG_COMPRA.AVANZAR('||P||','||A||',''LISTO_RECOGER'',NULL); END;',-20709);
 PKG_COMPRA.AVANZAR(P,A,'EN_ELABORACION',NULL); PKG_COMPRA.AVANZAR(P,A,'LISTO_RECOGER',NULL);
 FAIL('BEGIN PKG_COMPRA.FINALIZAR('||P||','||A||',''RECOGIDO'',''Cliente QA'',NULL,0,NULL); END;',-20700);
 SELECT COUNT(*) INTO N FROM ENTREGA WHERE ID_PEDIDO=P;OK(N=0,'fallo no deja entrega parcial');
 PKG_COMPRA.FINALIZAR(P,A,'RECOGIDO','Cliente QA',NULL,100,NULL);
 SELECT COUNT(*) INTO N FROM PAGO PG JOIN ESTADO_PAGO EP ON EP.ID_ESTADO_PAGO=PG.ID_ESTADO_PAGO WHERE PG.ID_PEDIDO=P AND EP.CODIGO='PAGADO_EFECTIVO';OK(N=1,'cobro efectivo confirmado');
 FAIL('BEGIN PKG_COMPRA.FINALIZAR('||P||','||A||',''RECOGIDO'',''Cliente QA'',NULL,100,NULL); END;',-20709);
 CART_NEW;
 PKG_COMPRA.CREAR(U,C,2,'55555555',NULL,'Guatemala','Guatemala','Dirección QA','Referencia QA','EFECTIVO','TEST',P2);
 SELECT CARGO_ENTREGA,TOTAL INTO N,V FROM PEDIDO WHERE ID_PEDIDO=P2;OK(N=25 AND V=125,'total domicilio');
 PKG_COMPRA.CORREGIR(P2,A,'55555556',NULL,'Guatemala','Guatemala','Dirección corregida','Referencia corregida','Llamada del cliente');
 SELECT COUNT(*) INTO N FROM PEDIDO_DATO_HISTORIAL WHERE ID_PEDIDO=P2;OK(N=1,'auditoría corrección');
 PKG_COMPRA.AVANZAR(P2,A,'EN_ELABORACION',NULL);PKG_COMPRA.AVANZAR(P2,A,'LISTO_ENTREGA',NULL);PKG_COMPRA.ASIGNAR(P2,A,R);
 FAIL('BEGIN PKG_COMPRA.ASIGNAR('||P2||','||A||','||R||'); END;',-20709);
 PKG_COMPRA.AVANZAR(P2,R,'EN_RUTA',NULL);
 PKG_COMPRA.FINALIZAR(P2,R,'COMPRADOR_NO_ENCONTRADO',NULL,NULL,0,'No respondió a la llamada.');
 PKG_COMPRA.ASIGNAR(P2,A,R);PKG_COMPRA.AVANZAR(P2,R,'EN_RUTA',NULL);
 FAIL('BEGIN PKG_COMPRA.FINALIZAR('||P2||','||R||',''ENTREGADO'',''Cliente QA'',NULL,125,NULL); END;',-20700);
 INSERT INTO ARCHIVO(ID_USUARIO_CARGA,TIPO_ARCHIVO,NOMBRE_ARCHIVO,MIME_TYPE,TAMANO_BYTES,CONTENIDO) VALUES(R,'EVIDENCIA_ENTREGA','qa.png','image/png',1,HEXTORAW('00')) RETURNING ID_ARCHIVO INTO ARCH;
 PKG_COMPRA.FINALIZAR(P2,R,'ENTREGADO','Cliente QA',ARCH,125,NULL);
 SELECT COUNT(*) INTO N FROM ENTREGA WHERE ID_PEDIDO=P2;OK(N=2,'dos intentos conservados');
 CART_NEW;
 PKG_COMPRA.CREAR(U,C,1,'55555555',NULL,NULL,NULL,NULL,NULL,'TARJETA','TEST',P3);
 UPDATE PAGO SET ID_CHECKOUT_PROVEEDOR='ch_qa_'||SUF WHERE ID_PEDIDO=P3;
 FAIL('BEGIN PKG_COMPRA.AVANZAR('||P3||','||A||',''EN_ELABORACION'',NULL); END;',-20709);
 FAIL('BEGIN PKG_COMPRA.CONFIRMAR_PAGO(''ch_qa_'||SUF||''',''TEST'',''evbad_'||SUF||''',''intent.succeeded'',''APROBADO'',1,''GTQ'',''pi_qa_'||SUF||'''); END;',-20709);
 PKG_COMPRA.CONFIRMAR_PAGO('ch_qa_'||SUF,'TEST','ev_'||SUF,'intent.succeeded','APROBADO',100,'GTQ','pi_qa_'||SUF);
 PKG_COMPRA.CONFIRMAR_PAGO('ch_qa_'||SUF,'TEST','ev_'||SUF,'intent.succeeded','APROBADO',100,'GTQ','pi_qa_'||SUF);
 PKG_COMPRA.CONFIRMAR_PAGO('ch_qa_'||SUF,'TEST','evfail_'||SUF,'intent.failed','RECHAZADO',100,'GTQ','pi_qa_'||SUF);
 SELECT COUNT(*) INTO N FROM PAGO PG JOIN ESTADO_PAGO EP ON EP.ID_ESTADO_PAGO=PG.ID_ESTADO_PAGO WHERE PG.ID_PEDIDO=P3 AND EP.CODIGO='APROBADO';OK(N=1,'fallo tardío no revierte pago');
 SELECT COUNT(*) INTO N FROM PAGO_EVENTO_PROVEEDOR WHERE ID_EVENTO_PROVEEDOR='ev_'||SUF;OK(N=1,'evento único');
 PKG_COMPRA.AVANZAR(P3,A,'EN_ELABORACION',NULL);PKG_COMPRA.AVANZAR(P3,A,'CANCELADO','Compra equivocada');
 SELECT COUNT(*) INTO N FROM PAGO PG JOIN ESTADO_PAGO EP ON EP.ID_ESTADO_PAGO=PG.ID_ESTADO_PAGO WHERE PG.ID_PEDIDO=P3 AND EP.CODIGO='REEMBOLSO_PENDIENTE';OK(N=1,'cancelación pagada requiere devolución');
 SELECT COUNT(*) INTO N FROM PAGO_ESTADO_HISTORIAL WHERE ID_PAGO IN (SELECT ID_PAGO FROM PAGO WHERE ID_PEDIDO=P3);OK(N>=3,'auditoría pago');
 ROLLBACK;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/
